#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Learn a branching regression tree from strong branching records (Issue #801).

Usage:
    python bench/runners/learned_branching_cart.py INPUT.csv OUTPUT.cpp OUTPUT.hpp

Reads the CSV emitted by mip_strong_branch_record_csv, filters to rows where both
directions were measured, calculates the true strong branching score, and trains
a shallow CART regression tree (MSE) on candidate features.
"""

import sys
import csv
import math

# The CSV emitted by Phase 1 has NO header. The columns are exactly:
# 0: u (variable index)
# 1: fractionality
# 2: objective_coefficient
# 3: column_degree
# 4: pc_down
# 5: pc_up
# 6: measured_down
# 7: measured_up
# 8: down (effective)
# 9: up (effective)
# 10: score (effective)
# 11: selected (1/0)

FEATURES = ["fractionality", "objective_coefficient", "column_degree", "pc_down", "pc_up"]
MAX_DEPTH = 4
MIN_LEAF = 5
EPSILON = 1e-6

def variance(rows):
    if not rows:
        return 0.0
    mean = sum(r["target"] for r in rows) / len(rows)
    return sum((r["target"] - mean) ** 2 for r in rows) / len(rows)

def nice_threshold(lo, hi):
    mid = (lo + hi) / 2.0
    a, b = lo + (hi - lo) / 4.0, hi - (hi - lo) / 4.0
    for digits in range(1, 18):
        candidate = float(f"{mid:.{digits}g}")
        if a <= candidate <= b:
            return candidate
    return mid

def best_split(rows):
    parent_var = variance(rows)
    best = None
    best_score = parent_var - 1e-12
    for f in range(len(FEATURES)):
        values = sorted({r["x"][f] for r in rows if math.isfinite(r["x"][f])})
        for lo, hi in zip(values, values[1:]):
            left = [r for r in rows if r["x"][f] <= lo]
            right = [r for r in rows if r["x"][f] > lo]
            if len(left) < MIN_LEAF or len(right) < MIN_LEAF:
                continue
            score = (len(left) * variance(left) + len(right) * variance(right)) / len(rows)
            if score < best_score:
                best, best_score = (f, nice_threshold(lo, hi)), score
    return best

def grow(rows, depth=0):
    mean_target = sum(r["target"] for r in rows) / len(rows) if rows else 0.0
    node = {"mean": mean_target, "samples": len(rows)}
    if depth >= MAX_DEPTH:
        return node
    
    split = best_split(rows)
    if split is None:
        return node
    
    f, t = split
    node["feature"], node["threshold"] = f, t
    node["left"] = grow([r for r in rows if r["x"][f] <= t], depth + 1)
    node["right"] = grow([r for r in rows if r["x"][f] > t], depth + 1)
    
    if "feature" not in node["left"] and "feature" not in node["right"] and node["left"]["mean"] == node["right"]["mean"]:
        del node["feature"]
        del node["threshold"]
        del node["left"]
        del node["right"]
        
    return node

def parse_csv(csv_path):
    rows = []
    with open(csv_path, newline="") as handle:
        reader = csv.reader(handle)
        for row_idx, raw in enumerate(reader):
            if not raw or len(raw) < 12:
                continue
            try:
                frac = float(raw[1])
                obj_coef = float(raw[2])
                degree = float(raw[3])
                pc_down = float(raw[4])
                pc_up = float(raw[5])
                measured_down = float(raw[6])
                measured_up = float(raw[7])
            except ValueError:
                continue
                
            if not math.isfinite(measured_down) or not math.isfinite(measured_up):
                continue
                
            if measured_down < 0.0 or measured_up < 0.0:
                continue
                
            target = max(measured_down, EPSILON) * max(measured_up, EPSILON)
            x = [frac, obj_coef, degree, pc_down, pc_up]
            
            if not all(math.isfinite(v) for v in x):
                continue
                
            rows.append({"x": x, "target": target})
    return rows

def generate_cpp_code(node, depth=1):
    indent = "  " * depth
    if "feature" not in node:
        return f"{indent}return {node['mean']:.6g};  // samples: {node['samples']}\n"
    
    feat_name = FEATURES[node['feature']]
    threshold = node['threshold']
    
    code = f"{indent}if ({feat_name} <= {threshold}) {{\n"
    code += generate_cpp_code(node['left'], depth + 1)
    code += f"{indent}}} else {{\n"
    code += generate_cpp_code(node['right'], depth + 1)
    code += f"{indent}}}\n"
    return code

def write_cpp(node, cpp_path, csv_path):
    with open(cpp_path, "w") as f:
        f.write("// SPDX-License-Identifier: Apache-2.0\n")
        f.write("// GENERATED FILE - DO NOT EDIT BY HAND\n")
        f.write(f"// Generated by bench/runners/learned_branching_cart.py from {csv_path}\n\n")
        f.write("#include \"learned_branching_rule.hpp\"\n\n")
        f.write("namespace sankhya {\n\n")
        f.write("double evaluate_learned_branching_rule(\n")
        f.write("    double fractionality,\n")
        f.write("    double objective_coefficient,\n")
        f.write("    double column_degree,\n")
        f.write("    double pc_down,\n")
        f.write("    double pc_up) {\n")
        f.write(generate_cpp_code(node))
        f.write("}\n\n")
        f.write("}  // namespace sankhya\n")

def write_hpp(hpp_path):
    with open(hpp_path, "w") as f:
        f.write("// SPDX-License-Identifier: Apache-2.0\n")
        f.write("#ifndef SANKHYA_MIP_LEARNED_BRANCHING_RULE_HPP_\n")
        f.write("#define SANKHYA_MIP_LEARNED_BRANCHING_RULE_HPP_\n\n")
        f.write("namespace sankhya {\n\n")
        f.write("// Evaluates the learned regression tree for strong branching.\n")
        f.write("double evaluate_learned_branching_rule(\n")
        f.write("    double fractionality,\n")
        f.write("    double objective_coefficient,\n")
        f.write("    double column_degree,\n")
        f.write("    double pc_down,\n")
        f.write("    double pc_up);\n\n")
        f.write("}  // namespace sankhya\n\n")
        f.write("#endif  // SANKHYA_MIP_LEARNED_BRANCHING_RULE_HPP_\n")

def run_self_test():
    print("Running synthetic self-test...")
    import tempfile
    import os
    with tempfile.TemporaryDirectory() as d:
        csv_path = os.path.join(d, "test.csv")
        cpp_path = os.path.join(d, "out.cpp")
        hpp_path = os.path.join(d, "out.hpp")
        
        with open(csv_path, "w") as f:
            # High score if pc_down and fractionality are both high
            for i in range(100):
                frac = i / 100.0
                obj_coef = 1.0
                deg = 5.0
                pcd = frac * 2.0
                pcu = 1.0
                md = pcd * 10
                mu = pcu * 10
                down = md
                up = mu
                score = max(down, EPSILON) * max(up, EPSILON)
                f.write(f"0,{frac},{obj_coef},{deg},{pcd},{pcu},{md},{mu},{down},{up},{score},0\n")
                
            # Throw in some unmeasured rows
            f.write("1,0.5,1.0,5.0,1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,0\n")
            
        rows = parse_csv(csv_path)
        assert len(rows) == 100
        tree = grow(rows)
        write_cpp(tree, cpp_path, csv_path)
        write_hpp(hpp_path)
        
        with open(cpp_path) as f:
            cpp_content = f.read()
            assert "if (fractionality" in cpp_content or "if (pc_down" in cpp_content
            assert "return" in cpp_content
            
    print("Self-test passed.")

if __name__ == "__main__":
    if len(sys.argv) == 1 or sys.argv[1] == "--test":
        run_self_test()
        sys.exit(0)
        
    if len(sys.argv) != 4:
        print("Usage: python learned_branching_cart.py INPUT.csv OUTPUT.cpp OUTPUT.hpp")
        sys.exit(1)
        
    in_csv = sys.argv[1]
    out_cpp = sys.argv[2]
    out_hpp = sys.argv[3]
    
    rows = parse_csv(in_csv)
    if not rows:
        print(f"Error: No usable measured rows found in {in_csv}.")
        sys.exit(1)
        
    tree = grow(rows)
    write_cpp(tree, out_cpp, in_csv)
    write_hpp(out_hpp)
    print(f"Generated {out_cpp} and {out_hpp} from {len(rows)} training rows.")
