#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the scoreboard at the top of README.md, from the CSVs in bench/results/ (#983).

A reader who stops after one screen of README.md gets the status table and the GPU
paragraph and none of the set counts: the first results table (Netlib) sits at line 77, the
QP sentence at line 260, MIPLIB 3 first named at line 283. The counts all exist, each with
its own CSV in bench/results/, but they are not in one place a reader sees first.

This script is that one place. One row per benchmark set that ALREADY HAS a committed CSV
in this repository - a set with no committed results CSV gets no row, rather than a
fabricated one. For each row:

*   `instances` - the distinct instances the newest committed CSV for that set covers.
*   `our count, under the set's stated grading` - the grading is READ FROM THE CSV, not
    invented here: the runner's own `passed` column where it has one (netlib, netlib
    infeasible, kennington, mittelmann, maros-meszaros, qplib - see bench/runners/netlib.py
    etc., each computing it the same way: matches the published or reference value within
    the project's tolerance AND tools/verify_solution.py accepted the point), or the
    equivalent pair of columns the set's own CSV carries when it has no single `passed`
    column (MIPLIB's `matched_published` + `independently_verified`, the stress set's
    `verdict`, a GPU card's own arm beating the faster CPU arm on the same instance).
*   `reference solver on the same host` - the external solver named in the CSV, when the
    CSV records one (HiGHS for MIPLIB 3's comparison run, the `reference_source` a GPU run
    checks its objective against); `-` when the CSV carries no second solver, as the LP,
    QP and stress CSVs do not (#766's five-solver head-to-head is reported separately, in
    docs/BENCHMARKS.md section 4a, not duplicated here).
*   `CSV`, `commit`, `date` - exactly what the newest matching CSV says, so every cell is
    one click from the file that produced it.

Usage:

    python bench/runners/make_scoreboard.py            # print the table
    python bench/runners/make_scoreboard.py --check     # exit 1 if README.md disagrees
    python bench/runners/make_scoreboard.py --write      # update README.md in place
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import latest_result  # noqa: E402
import miplib3_doc  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
README = REPO_ROOT / "README.md"
RESULTS_DIR = REPO_ROOT / "bench" / "results"

START_MARKER = "<!-- scoreboard:start (generated by bench/runners/make_scoreboard.py; do not edit by hand) -->"
END_MARKER = "<!-- scoreboard:end -->"


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def first_row(rows: list[dict]) -> dict:
    return rows[0] if rows else {}


def date_of(row: dict) -> str:
    ts = row.get("timestamp_utc", "")
    return ts.split("T", 1)[0] if ts else "-"


def passed_column(rows: list[dict], key: str = "passed") -> tuple[int, int]:
    """(distinct instances passed, distinct instances total), from a 0/1 `passed`-shaped
    column: an instance counts as passed if ANY of its rows (there is normally one) says
    so, by this set's own runner (see the module docstring)."""
    by_instance: dict[str, bool] = {}
    for row in rows:
        name = row["instance"]
        ok = row.get(key) in ("1", 1, True)
        by_instance[name] = by_instance.get(name, False) or ok
    return sum(by_instance.values()), len(by_instance)


def passed_predicate(rows: list[dict], predicate) -> tuple[int, int]:
    by_instance: dict[str, bool] = {}
    for row in rows:
        name = row["instance"]
        ok = predicate(row)
        by_instance[name] = by_instance.get(name, False) or ok
    return sum(by_instance.values()), len(by_instance)


class Row:
    def __init__(self, label: str, path: Path, passed: int, total: int, grading: str,
                 reference: str):
        self.label, self.path, self.passed, self.total = label, path, passed, total
        self.grading, self.reference = grading, reference
        rows = read_csv(path)
        first = first_row(rows)
        self.commit = first.get("git_commit", "-") or "-"
        self.date = date_of(first)

    def markdown(self) -> str:
        return (f"| {self.label} | {self.total} | **{self.passed} of {self.total}** "
                f"({self.grading}) | {self.reference} | "
                f"`bench/results/{self.path.name}` | `{self.commit}` | {self.date} |")


def netlib_row() -> Row | None:
    path = latest_result.latest("netlib-full-*.csv", prefix="netlib-full")
    if path is None:
        return None
    passed, total = passed_column(read_csv(path))
    return Row("Netlib", path, passed, total,
               "exact optimum and verified, `passed`", "-")


def netlib_infeasible_row() -> Row | None:
    path = latest_result.latest("netlib-infeasible-*.csv", prefix="netlib-infeasible")
    if path is None:
        return None
    passed, total = passed_column(read_csv(path))
    return Row("Netlib infeasible", path, passed, total,
               "certified infeasible, `passed`", "-")


def kennington_row() -> Row | None:
    path = (latest_result.latest("kennington-full-*.csv", prefix="kennington-full")
            or latest_result.latest("kennington-small-*.csv", prefix="kennington-small"))
    if path is None:
        return None
    passed, total = passed_column(read_csv(path))
    return Row("Kennington", path, passed, total,
               "matches published optimum and verified, `passed`", "-")


def mittelmann_row() -> Row | None:
    path = latest_result.latest("mittelmann-*.csv", prefix="mittelmann")
    if path is None:
        return None
    rows = [r for r in read_csv(path) if "reference_source" not in r
            or True]  # the plain mittelmann.py CSV, not a *-ab-* A/B variant
    passed, total = passed_column(rows)
    reference = sorted({r.get("algorithm", "") for r in rows if r.get("algorithm")})
    return Row("Mittelmann", path, passed, total,
               "matches HiGHS's objective and verified, `passed`", "HiGHS (objective check)")


def maros_meszaros_row() -> Row | None:
    path = latest_result.latest("maros-meszaros-*.csv", prefix="maros-meszaros")
    if path is None:
        return None
    rows = read_csv(path)
    # Leave out the A/B and engine-specific variants (maros-meszaros-493-*, *-cv-*,
    # *-ipm-*): their names carry an option, not the headline run's.
    passed, total = passed_column(rows)
    return Row("Maros-Meszaros (QP)", path, passed, total,
               "within relative 1e-6 of the reference and verified, `passed`", "-")


def qplib_row() -> Row | None:
    path = (latest_result.latest("qplib-*.csv", prefix="qplib")
            or latest_result.latest("qplib-small-*.csv", prefix="qplib-small"))
    if path is None:
        return None
    rows = read_csv(path)
    judged = [r for r in rows if r.get("passed", "") != ""]
    passed, total = passed_column(judged)
    return Row("QPLIB (convex)", path, passed, total,
               "within relative 1e-6 of the published or best-known value and verified, "
               "`passed`", "-")


def miplib_row() -> Row | None:
    path = latest_result.latest("miplib-*.csv", prefix="miplib")
    if path is None:
        return None
    rows = read_csv(path)
    passed, total = passed_predicate(
        rows, lambda r: r.get("matched_published") == "1"
        and r.get("independently_verified") == "1")
    return Row("MIPLIB 2017", path, passed, total,
               "matched the published optimum and verified", "-")


def miplib3_row() -> Row | None:
    path = latest_result.latest(miplib3_doc.sankhya_pattern(300))
    if path is None:
        return None
    rows = read_csv(path)
    passed, total = passed_predicate(
        rows, lambda r: r.get("matched_published") == "1"
        and r.get("independently_verified") == "1")
    highs = latest_result.latest(miplib3_doc.highs_pattern(300))
    reference = "HiGHS (same host)" if highs else "-"
    return Row("MIPLIB 3", path, passed, total,
               "matched the published optimum and verified, best of 3 seeds", reference)


def stress_row() -> Row | None:
    path = latest_result.latest("stress-*.csv", prefix="stress")
    if path is None:
        return None
    rows = [r for r in read_csv(path) if r.get("solver") == "sankhya"]
    if not rows:
        return None
    passed, total = passed_predicate(rows, lambda r: r.get("verdict") == "correct")
    return Row("Stress set", path, passed, total, "verdict `correct`", "-")


def gpu_rows() -> list[Row]:
    """One row per card gpu-real-<card>-<sha>.csv names (#390, #424, #488): the instances
    on which the GPU arm's own clock (`seconds`) beat the fastest CPU arm's on the same
    instance, out of the instances that card's run covers. `reference_source` is the
    objective-checking reference the CSV itself records (HiGHS throughout), not a speed
    comparison - the speed comparison is against our own CPU arm, stated as such."""
    out = []
    seen_cards = set()
    for path in sorted(RESULTS_DIR.glob("gpu-real-*.csv")):
        name = path.stem  # gpu-real-<card>-<sha>
        parts = name.split("-")
        if len(parts) < 4:
            continue
        card = parts[2]
        if card in seen_cards:
            continue
        newest = latest_result.latest(f"gpu-real-{card}-*.csv", prefix=f"gpu-real-{card}")
        if newest is None:
            continue
        seen_cards.add(card)
        rows = read_csv(newest)
        by_instance: dict[str, dict[str, float]] = {}
        for row in rows:
            try:
                seconds = float(row["seconds"])
            except (KeyError, ValueError):
                continue
            by_instance.setdefault(row["instance"], {})[row.get("arm", "")] = seconds
        faster, total = 0, 0
        for instance, arms in by_instance.items():
            gpu_time = arms.get("gpu")
            cpu_times = [v for k, v in arms.items() if k != "gpu"]
            if gpu_time is None or not cpu_times:
                continue
            total += 1
            faster += gpu_time < min(cpu_times)
        if total == 0:
            continue
        sources = sorted({r.get("reference_source", "") for r in rows
                          if r.get("reference_source")})
        reference = ", ".join(sources) if sources else "-"
        out.append(Row(f"GPU, real instances ({card.upper()})", newest, faster, total,
                       "faster than the faster CPU arm on the same instance", reference))
    return out


def all_rows() -> list[Row]:
    rows = [netlib_row(), netlib_infeasible_row(), kennington_row(), mittelmann_row(),
            miplib3_row(), miplib_row(), maros_meszaros_row(), qplib_row(), stress_row()]
    rows = [r for r in rows if r is not None]
    rows += gpu_rows()
    return rows


def render() -> str:
    rows = all_rows()
    lines = [START_MARKER,
             "**Scoreboard, generated from the CSVs in `bench/results/` by "
             "`bench/runners/make_scoreboard.py`; a row here only for a set with a "
             "committed results CSV, and regenerated, never hand-edited.**",
             "",
             "| set | instances | our count, under the set's stated grading | reference "
             "solver on the same host | CSV | commit | date |",
             "|---|---:|---|---|---|---|---|"]
    lines += [row.markdown() for row in rows]
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def splice(readme_text: str, table: str) -> str:
    """Insert or replace the scoreboard block, idempotently: splicing the same table in
    twice produces the same text both times (checked by test_make_scoreboard.py), which
    the CI check relies on to compare the README's block against a freshly rendered one
    byte for byte. `block` is always exactly START_MARKER..END_MARKER plus one trailing
    newline, regardless of how many `table` itself happens to end with."""
    block = table.rstrip("\n") + "\n"
    start = readme_text.find(START_MARKER)
    if start != -1:
        end = readme_text.find(END_MARKER, start)
        if end != -1:
            end += len(END_MARKER)
            if end < len(readme_text) and readme_text[end] == "\n":
                end += 1
            return readme_text[:start] + block + readme_text[end:]
    # First run: insert right after the title block's closing `---` (the end of the quoted
    # PROVENANCE.md paragraph), under the title and above "## Status".
    marker = "\n---\n"
    at = readme_text.find(marker)
    if at == -1:
        return block + "\n" + readme_text
    at += len(marker)
    return readme_text[:at] + "\n" + block + readme_text[at:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if README.md's table differs from what the CSVs give")
    parser.add_argument("--write", action="store_true", help="update README.md in place")
    args = parser.parse_args()
    table = render()
    if args.write:
        current = README.read_text(encoding="utf-8")
        README.write_text(splice(current, table), encoding="utf-8")
        print(f"wrote {README.relative_to(REPO_ROOT)}")
        return 0
    if args.check:
        current = README.read_text(encoding="utf-8")
        start, end = current.find(START_MARKER), current.find(END_MARKER)
        if start == -1 or end == -1:
            print("README.md has no scoreboard block "
                 "(run: python bench/runners/make_scoreboard.py --write)")
            return 1
        existing = current[start:end + len(END_MARKER)]
        if existing.strip() != table.strip():
            print("README.md's scoreboard is stale against bench/results/*.csv on this "
                 "commit (run: python bench/runners/make_scoreboard.py --write)")
            return 1
        print("README.md's scoreboard matches bench/results/*.csv on this commit")
        return 0
    print(table)
    return 0


if __name__ == "__main__":
    sys.exit(main())
