* SANKHYA pooling instance adhya2, PQ-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/adhya2.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Adhya2.gms
* (sha256 cda74c990c3cccea74cd9850d0eb47a155029675341fc7ea9b1fde7b371f195f).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* PQ-formulation (Quesada and Grossmann 1995; Tawarmalani and Sahinidis 2002)
NAME adhya2_pq
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L src_5
 L dem_8
 L dem_9
 L dem_10
 L dem_11
 E sumq_6
 L cap_6
 E sumq_7
 L cap_7
 L tq_8_1
 L tq_8_2
 L tq_8_3
 L tq_8_4
 L tq_8_5
 L tq_8_6
 L tq_9_1
 L tq_9_2
 L tq_9_3
 L tq_9_4
 L tq_9_5
 L tq_9_6
 L tq_10_1
 L tq_10_2
 L tq_10_3
 L tq_10_4
 L tq_10_5
 L tq_10_6
 L tq_11_1
 L tq_11_2
 L tq_11_3
 L tq_11_4
 L tq_11_5
 L tq_11_6
 E path_1_6_8
 E path_1_6_9
 E path_1_6_10
 E path_1_6_11
 E path_2_6_8
 E path_2_6_9
 E path_2_6_10
 E path_2_6_11
 E path_3_7_8
 E path_3_7_9
 E path_3_7_10
 E path_3_7_11
 E path_4_7_8
 E path_4_7_9
 E path_4_7_10
 E path_4_7_11
 E path_5_7_8
 E path_5_7_9
 E path_5_7_10
 E path_5_7_11
 E rlt_6_8
 E rlt_6_9
 E rlt_6_10
 E rlt_6_11
 L rltc_1_6
 L rltc_2_6
 E rlt_7_8
 E rlt_7_9
 E rlt_7_10
 E rlt_7_11
 L rltc_3_7
 L rltc_4_7
 L rltc_5_7
COLUMNS
 q_1_6 sumq_6 1
 q_1_6 rltc_1_6 -75
 q_2_6 sumq_6 1
 q_2_6 rltc_2_6 -75
 q_3_7 sumq_7 1
 q_3_7 rltc_3_7 -75
 q_4_7 sumq_7 1
 q_4_7 rltc_4_7 -75
 q_5_7 sumq_7 1
 q_5_7 rltc_5_7 -75
 f_6_8 cost -16
 f_6_8 dem_8 1
 f_6_8 cap_6 1
 f_6_8 tq_8_1 -3
 f_6_8 tq_8_2 -3
 f_6_8 tq_8_3 -3.25
 f_6_8 tq_8_4 -0.75
 f_6_8 tq_8_5 -6
 f_6_8 tq_8_6 -5
 f_6_8 rlt_6_8 -1
 f_6_9 cost -25
 f_6_9 dem_9 1
 f_6_9 cap_6 1
 f_6_9 tq_9_1 -4
 f_6_9 tq_9_2 -2.5
 f_6_9 tq_9_3 -3.5
 f_6_9 tq_9_4 -1.5
 f_6_9 tq_9_5 -7
 f_6_9 tq_9_6 -6
 f_6_9 rlt_6_9 -1
 f_6_10 cost -15
 f_6_10 dem_10 1
 f_6_10 cap_6 1
 f_6_10 tq_10_1 -1.5
 f_6_10 tq_10_2 -5.5
 f_6_10 tq_10_3 -3.9
 f_6_10 tq_10_4 -0.8
 f_6_10 tq_10_5 -7
 f_6_10 tq_10_6 -6
 f_6_10 rlt_6_10 -1
 f_6_11 cost -10
 f_6_11 dem_11 1
 f_6_11 cap_6 1
 f_6_11 tq_11_1 -3
 f_6_11 tq_11_2 -4
 f_6_11 tq_11_3 -4
 f_6_11 tq_11_4 -1.8
 f_6_11 tq_11_5 -8
 f_6_11 tq_11_6 -6
 f_6_11 rlt_6_11 -1
 f_7_8 cost -16
 f_7_8 dem_8 1
 f_7_8 cap_7 1
 f_7_8 tq_8_1 -3
 f_7_8 tq_8_2 -3
 f_7_8 tq_8_3 -3.25
 f_7_8 tq_8_4 -0.75
 f_7_8 tq_8_5 -6
 f_7_8 tq_8_6 -5
 f_7_8 rlt_7_8 -1
 f_7_9 cost -25
 f_7_9 dem_9 1
 f_7_9 cap_7 1
 f_7_9 tq_9_1 -4
 f_7_9 tq_9_2 -2.5
 f_7_9 tq_9_3 -3.5
 f_7_9 tq_9_4 -1.5
 f_7_9 tq_9_5 -7
 f_7_9 tq_9_6 -6
 f_7_9 rlt_7_9 -1
 f_7_10 cost -15
 f_7_10 dem_10 1
 f_7_10 cap_7 1
 f_7_10 tq_10_1 -1.5
 f_7_10 tq_10_2 -5.5
 f_7_10 tq_10_3 -3.9
 f_7_10 tq_10_4 -0.8
 f_7_10 tq_10_5 -7
 f_7_10 tq_10_6 -6
 f_7_10 rlt_7_10 -1
 f_7_11 cost -10
 f_7_11 dem_11 1
 f_7_11 cap_7 1
 f_7_11 tq_11_1 -3
 f_7_11 tq_11_2 -4
 f_7_11 tq_11_3 -4
 f_7_11 tq_11_4 -1.8
 f_7_11 tq_11_5 -8
 f_7_11 tq_11_6 -6
 f_7_11 rlt_7_11 -1
 v_1_6_8 cost 7
 v_1_6_8 src_1 1
 v_1_6_8 tq_8_1 1
 v_1_6_8 tq_8_2 6
 v_1_6_8 tq_8_3 4
 v_1_6_8 tq_8_4 0.5
 v_1_6_8 tq_8_5 5
 v_1_6_8 tq_8_6 9
 v_1_6_8 path_1_6_8 1
 v_1_6_8 rlt_6_8 1
 v_1_6_8 rltc_1_6 1
 v_1_6_9 cost 7
 v_1_6_9 src_1 1
 v_1_6_9 tq_9_1 1
 v_1_6_9 tq_9_2 6
 v_1_6_9 tq_9_3 4
 v_1_6_9 tq_9_4 0.5
 v_1_6_9 tq_9_5 5
 v_1_6_9 tq_9_6 9
 v_1_6_9 path_1_6_9 1
 v_1_6_9 rlt_6_9 1
 v_1_6_9 rltc_1_6 1
 v_1_6_10 cost 7
 v_1_6_10 src_1 1
 v_1_6_10 tq_10_1 1
 v_1_6_10 tq_10_2 6
 v_1_6_10 tq_10_3 4
 v_1_6_10 tq_10_4 0.5
 v_1_6_10 tq_10_5 5
 v_1_6_10 tq_10_6 9
 v_1_6_10 path_1_6_10 1
 v_1_6_10 rlt_6_10 1
 v_1_6_10 rltc_1_6 1
 v_1_6_11 cost 7
 v_1_6_11 src_1 1
 v_1_6_11 tq_11_1 1
 v_1_6_11 tq_11_2 6
 v_1_6_11 tq_11_3 4
 v_1_6_11 tq_11_4 0.5
 v_1_6_11 tq_11_5 5
 v_1_6_11 tq_11_6 9
 v_1_6_11 path_1_6_11 1
 v_1_6_11 rlt_6_11 1
 v_1_6_11 rltc_1_6 1
 v_2_6_8 cost 3
 v_2_6_8 src_2 1
 v_2_6_8 tq_8_1 4
 v_2_6_8 tq_8_2 1
 v_2_6_8 tq_8_3 3
 v_2_6_8 tq_8_4 2
 v_2_6_8 tq_8_5 4
 v_2_6_8 tq_8_6 4
 v_2_6_8 path_2_6_8 1
 v_2_6_8 rlt_6_8 1
 v_2_6_8 rltc_2_6 1
 v_2_6_9 cost 3
 v_2_6_9 src_2 1
 v_2_6_9 tq_9_1 4
 v_2_6_9 tq_9_2 1
 v_2_6_9 tq_9_3 3
 v_2_6_9 tq_9_4 2
 v_2_6_9 tq_9_5 4
 v_2_6_9 tq_9_6 4
 v_2_6_9 path_2_6_9 1
 v_2_6_9 rlt_6_9 1
 v_2_6_9 rltc_2_6 1
 v_2_6_10 cost 3
 v_2_6_10 src_2 1
 v_2_6_10 tq_10_1 4
 v_2_6_10 tq_10_2 1
 v_2_6_10 tq_10_3 3
 v_2_6_10 tq_10_4 2
 v_2_6_10 tq_10_5 4
 v_2_6_10 tq_10_6 4
 v_2_6_10 path_2_6_10 1
 v_2_6_10 rlt_6_10 1
 v_2_6_10 rltc_2_6 1
 v_2_6_11 cost 3
 v_2_6_11 src_2 1
 v_2_6_11 tq_11_1 4
 v_2_6_11 tq_11_2 1
 v_2_6_11 tq_11_3 3
 v_2_6_11 tq_11_4 2
 v_2_6_11 tq_11_5 4
 v_2_6_11 tq_11_6 4
 v_2_6_11 path_2_6_11 1
 v_2_6_11 rlt_6_11 1
 v_2_6_11 rltc_2_6 1
 v_3_7_8 cost 2
 v_3_7_8 src_3 1
 v_3_7_8 tq_8_1 4
 v_3_7_8 tq_8_2 5.5
 v_3_7_8 tq_8_3 3
 v_3_7_8 tq_8_4 0.9
 v_3_7_8 tq_8_5 7
 v_3_7_8 tq_8_6 10
 v_3_7_8 path_3_7_8 1
 v_3_7_8 rlt_7_8 1
 v_3_7_8 rltc_3_7 1
 v_3_7_9 cost 2
 v_3_7_9 src_3 1
 v_3_7_9 tq_9_1 4
 v_3_7_9 tq_9_2 5.5
 v_3_7_9 tq_9_3 3
 v_3_7_9 tq_9_4 0.9
 v_3_7_9 tq_9_5 7
 v_3_7_9 tq_9_6 10
 v_3_7_9 path_3_7_9 1
 v_3_7_9 rlt_7_9 1
 v_3_7_9 rltc_3_7 1
 v_3_7_10 cost 2
 v_3_7_10 src_3 1
 v_3_7_10 tq_10_1 4
 v_3_7_10 tq_10_2 5.5
 v_3_7_10 tq_10_3 3
 v_3_7_10 tq_10_4 0.9
 v_3_7_10 tq_10_5 7
 v_3_7_10 tq_10_6 10
 v_3_7_10 path_3_7_10 1
 v_3_7_10 rlt_7_10 1
 v_3_7_10 rltc_3_7 1
 v_3_7_11 cost 2
 v_3_7_11 src_3 1
 v_3_7_11 tq_11_1 4
 v_3_7_11 tq_11_2 5.5
 v_3_7_11 tq_11_3 3
 v_3_7_11 tq_11_4 0.9
 v_3_7_11 tq_11_5 7
 v_3_7_11 tq_11_6 10
 v_3_7_11 path_3_7_11 1
 v_3_7_11 rlt_7_11 1
 v_3_7_11 rltc_3_7 1
 v_4_7_8 cost 10
 v_4_7_8 src_4 1
 v_4_7_8 tq_8_1 3
 v_4_7_8 tq_8_2 3
 v_4_7_8 tq_8_3 3
 v_4_7_8 tq_8_4 1
 v_4_7_8 tq_8_5 3
 v_4_7_8 tq_8_6 4
 v_4_7_8 path_4_7_8 1
 v_4_7_8 rlt_7_8 1
 v_4_7_8 rltc_4_7 1
 v_4_7_9 cost 10
 v_4_7_9 src_4 1
 v_4_7_9 tq_9_1 3
 v_4_7_9 tq_9_2 3
 v_4_7_9 tq_9_3 3
 v_4_7_9 tq_9_4 1
 v_4_7_9 tq_9_5 3
 v_4_7_9 tq_9_6 4
 v_4_7_9 path_4_7_9 1
 v_4_7_9 rlt_7_9 1
 v_4_7_9 rltc_4_7 1
 v_4_7_10 cost 10
 v_4_7_10 src_4 1
 v_4_7_10 tq_10_1 3
 v_4_7_10 tq_10_2 3
 v_4_7_10 tq_10_3 3
 v_4_7_10 tq_10_4 1
 v_4_7_10 tq_10_5 3
 v_4_7_10 tq_10_6 4
 v_4_7_10 path_4_7_10 1
 v_4_7_10 rlt_7_10 1
 v_4_7_10 rltc_4_7 1
 v_4_7_11 cost 10
 v_4_7_11 src_4 1
 v_4_7_11 tq_11_1 3
 v_4_7_11 tq_11_2 3
 v_4_7_11 tq_11_3 3
 v_4_7_11 tq_11_4 1
 v_4_7_11 tq_11_5 3
 v_4_7_11 tq_11_6 4
 v_4_7_11 path_4_7_11 1
 v_4_7_11 rlt_7_11 1
 v_4_7_11 rltc_4_7 1
 v_5_7_8 cost 5
 v_5_7_8 src_5 1
 v_5_7_8 tq_8_1 1
 v_5_7_8 tq_8_2 2.7
 v_5_7_8 tq_8_3 4
 v_5_7_8 tq_8_4 1.6
 v_5_7_8 tq_8_5 3
 v_5_7_8 tq_8_6 7
 v_5_7_8 path_5_7_8 1
 v_5_7_8 rlt_7_8 1
 v_5_7_8 rltc_5_7 1
 v_5_7_9 cost 5
 v_5_7_9 src_5 1
 v_5_7_9 tq_9_1 1
 v_5_7_9 tq_9_2 2.7
 v_5_7_9 tq_9_3 4
 v_5_7_9 tq_9_4 1.6
 v_5_7_9 tq_9_5 3
 v_5_7_9 tq_9_6 7
 v_5_7_9 path_5_7_9 1
 v_5_7_9 rlt_7_9 1
 v_5_7_9 rltc_5_7 1
 v_5_7_10 cost 5
 v_5_7_10 src_5 1
 v_5_7_10 tq_10_1 1
 v_5_7_10 tq_10_2 2.7
 v_5_7_10 tq_10_3 4
 v_5_7_10 tq_10_4 1.6
 v_5_7_10 tq_10_5 3
 v_5_7_10 tq_10_6 7
 v_5_7_10 path_5_7_10 1
 v_5_7_10 rlt_7_10 1
 v_5_7_10 rltc_5_7 1
 v_5_7_11 cost 5
 v_5_7_11 src_5 1
 v_5_7_11 tq_11_1 1
 v_5_7_11 tq_11_2 2.7
 v_5_7_11 tq_11_3 4
 v_5_7_11 tq_11_4 1.6
 v_5_7_11 tq_11_5 3
 v_5_7_11 tq_11_6 7
 v_5_7_11 path_5_7_11 1
 v_5_7_11 rlt_7_11 1
 v_5_7_11 rltc_5_7 1
RHS
 rhs src_1 75
 rhs src_2 75
 rhs src_3 75
 rhs src_4 75
 rhs src_5 75
 rhs dem_8 10
 rhs dem_9 25
 rhs dem_10 30
 rhs dem_11 10
 rhs sumq_6 1
 rhs cap_6 75
 rhs sumq_7 1
 rhs cap_7 75
BOUNDS
 UP bnd q_1_6 1
 UP bnd q_2_6 1
 UP bnd q_3_7 1
 UP bnd q_4_7 1
 UP bnd q_5_7 1
 UP bnd f_6_8 10
 UP bnd f_6_9 25
 UP bnd f_6_10 30
 UP bnd f_6_11 10
 UP bnd f_7_8 10
 UP bnd f_7_9 25
 UP bnd f_7_10 30
 UP bnd f_7_11 10
 UP bnd v_1_6_8 10
 UP bnd v_1_6_9 25
 UP bnd v_1_6_10 30
 UP bnd v_1_6_11 10
 UP bnd v_2_6_8 10
 UP bnd v_2_6_9 25
 UP bnd v_2_6_10 30
 UP bnd v_2_6_11 10
 UP bnd v_3_7_8 10
 UP bnd v_3_7_9 25
 UP bnd v_3_7_10 30
 UP bnd v_3_7_11 10
 UP bnd v_4_7_8 10
 UP bnd v_4_7_9 25
 UP bnd v_4_7_10 30
 UP bnd v_4_7_11 10
 UP bnd v_5_7_8 10
 UP bnd v_5_7_9 25
 UP bnd v_5_7_10 30
 UP bnd v_5_7_11 10
QCMATRIX path_1_6_8
 f_6_8 q_1_6 -0.5
 q_1_6 f_6_8 -0.5
QCMATRIX path_1_6_9
 f_6_9 q_1_6 -0.5
 q_1_6 f_6_9 -0.5
QCMATRIX path_1_6_10
 f_6_10 q_1_6 -0.5
 q_1_6 f_6_10 -0.5
QCMATRIX path_1_6_11
 f_6_11 q_1_6 -0.5
 q_1_6 f_6_11 -0.5
QCMATRIX path_2_6_8
 f_6_8 q_2_6 -0.5
 q_2_6 f_6_8 -0.5
QCMATRIX path_2_6_9
 f_6_9 q_2_6 -0.5
 q_2_6 f_6_9 -0.5
QCMATRIX path_2_6_10
 f_6_10 q_2_6 -0.5
 q_2_6 f_6_10 -0.5
QCMATRIX path_2_6_11
 f_6_11 q_2_6 -0.5
 q_2_6 f_6_11 -0.5
QCMATRIX path_3_7_8
 f_7_8 q_3_7 -0.5
 q_3_7 f_7_8 -0.5
QCMATRIX path_3_7_9
 f_7_9 q_3_7 -0.5
 q_3_7 f_7_9 -0.5
QCMATRIX path_3_7_10
 f_7_10 q_3_7 -0.5
 q_3_7 f_7_10 -0.5
QCMATRIX path_3_7_11
 f_7_11 q_3_7 -0.5
 q_3_7 f_7_11 -0.5
QCMATRIX path_4_7_8
 f_7_8 q_4_7 -0.5
 q_4_7 f_7_8 -0.5
QCMATRIX path_4_7_9
 f_7_9 q_4_7 -0.5
 q_4_7 f_7_9 -0.5
QCMATRIX path_4_7_10
 f_7_10 q_4_7 -0.5
 q_4_7 f_7_10 -0.5
QCMATRIX path_4_7_11
 f_7_11 q_4_7 -0.5
 q_4_7 f_7_11 -0.5
QCMATRIX path_5_7_8
 f_7_8 q_5_7 -0.5
 q_5_7 f_7_8 -0.5
QCMATRIX path_5_7_9
 f_7_9 q_5_7 -0.5
 q_5_7 f_7_9 -0.5
QCMATRIX path_5_7_10
 f_7_10 q_5_7 -0.5
 q_5_7 f_7_10 -0.5
QCMATRIX path_5_7_11
 f_7_11 q_5_7 -0.5
 q_5_7 f_7_11 -0.5
ENDATA
