* SANKHYA pooling instance adhya4, P-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/adhya4.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Adhya4.gms
* (sha256 9da63c038eb6a921e3ed2d9fdfe03f0b065dfdaba9c0ac2b2c5dfd2e9f8ad4f2).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* P-formulation (Haverly 1978; Tawarmalani and Sahinidis 2002, ch. 9)
NAME adhya4_p
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L src_5
 L src_6
 L src_7
 L src_8
 L dem_11
 L dem_12
 L dem_13
 L dem_14
 L dem_15
 E bal_9
 L cap_9
 E pq_9_1
 E pq_9_2
 E pq_9_3
 E pq_9_4
 E bal_10
 L cap_10
 E pq_10_1
 E pq_10_2
 E pq_10_3
 E pq_10_4
 L tq_11_1
 L tq_11_2
 L tq_11_3
 L tq_11_4
 L tq_12_1
 L tq_12_2
 L tq_12_3
 L tq_12_4
 L tq_13_1
 L tq_13_2
 L tq_13_3
 L tq_13_4
 L tq_14_1
 L tq_14_2
 L tq_14_3
 L tq_14_4
 L tq_15_1
 L tq_15_2
 L tq_15_3
 L tq_15_4
COLUMNS
 f_1_9 cost 15
 f_1_9 src_1 1
 f_1_9 bal_9 1
 f_1_9 cap_9 1
 f_1_9 pq_9_1 0.5
 f_1_9 pq_9_2 1.9
 f_1_9 pq_9_3 1.3
 f_1_9 pq_9_4 1
 f_2_9 cost 7
 f_2_9 src_2 1
 f_2_9 bal_9 1
 f_2_9 cap_9 1
 f_2_9 pq_9_1 1.4
 f_2_9 pq_9_2 1.8
 f_2_9 pq_9_3 1.7
 f_2_9 pq_9_4 1.6
 f_3_9 cost 4
 f_3_9 src_3 1
 f_3_9 bal_9 1
 f_3_9 cap_9 1
 f_3_9 pq_9_1 1.2
 f_3_9 pq_9_2 1.9
 f_3_9 pq_9_3 1.4
 f_3_9 pq_9_4 1.4
 f_4_9 cost 5
 f_4_9 src_4 1
 f_4_9 bal_9 1
 f_4_9 cap_9 1
 f_4_9 pq_9_1 1.5
 f_4_9 pq_9_2 1.2
 f_4_9 pq_9_3 1.7
 f_4_9 pq_9_4 1.3
 f_5_10 cost 6
 f_5_10 src_5 1
 f_5_10 bal_10 1
 f_5_10 cap_10 1
 f_5_10 pq_10_1 1.6
 f_5_10 pq_10_2 1.8
 f_5_10 pq_10_3 1.6
 f_5_10 pq_10_4 2
 f_6_10 cost 3
 f_6_10 src_6 1
 f_6_10 bal_10 1
 f_6_10 cap_10 1
 f_6_10 pq_10_1 1.2
 f_6_10 pq_10_2 1.1
 f_6_10 pq_10_3 1.4
 f_6_10 pq_10_4 2
 f_7_10 cost 5
 f_7_10 src_7 1
 f_7_10 bal_10 1
 f_7_10 cap_10 1
 f_7_10 pq_10_1 1.5
 f_7_10 pq_10_2 1.5
 f_7_10 pq_10_3 1.5
 f_7_10 pq_10_4 1.5
 f_8_10 cost 5
 f_8_10 src_8 1
 f_8_10 bal_10 1
 f_8_10 cap_10 1
 f_8_10 pq_10_1 1.4
 f_8_10 pq_10_2 1.6
 f_8_10 pq_10_3 1.2
 f_8_10 pq_10_4 1.6
 f_9_11 cost -10
 f_9_11 dem_11 1
 f_9_11 bal_9 -1
 f_9_11 tq_11_1 -1.2
 f_9_11 tq_11_2 -1.7
 f_9_11 tq_11_3 -1.4
 f_9_11 tq_11_4 -1.7
 f_9_12 cost -25
 f_9_12 dem_12 1
 f_9_12 bal_9 -1
 f_9_12 tq_12_1 -1.4
 f_9_12 tq_12_2 -1.3
 f_9_12 tq_12_3 -1.8
 f_9_12 tq_12_4 -1.4
 f_9_13 cost -30
 f_9_13 dem_13 1
 f_9_13 bal_9 -1
 f_9_13 tq_13_1 -1.3
 f_9_13 tq_13_2 -1.3
 f_9_13 tq_13_3 -1.9
 f_9_13 tq_13_4 -1.9
 f_9_14 cost -6
 f_9_14 dem_14 1
 f_9_14 bal_9 -1
 f_9_14 tq_14_1 -1.2
 f_9_14 tq_14_2 -1.1
 f_9_14 tq_14_3 -1.7
 f_9_14 tq_14_4 -1.6
 f_9_15 cost -10
 f_9_15 dem_15 1
 f_9_15 bal_9 -1
 f_9_15 tq_15_1 -1.6
 f_9_15 tq_15_2 -1.9
 f_9_15 tq_15_3 -2
 f_9_15 tq_15_4 -2.5
 f_10_11 cost -10
 f_10_11 dem_11 1
 f_10_11 bal_10 -1
 f_10_11 tq_11_1 -1.2
 f_10_11 tq_11_2 -1.7
 f_10_11 tq_11_3 -1.4
 f_10_11 tq_11_4 -1.7
 f_10_12 cost -25
 f_10_12 dem_12 1
 f_10_12 bal_10 -1
 f_10_12 tq_12_1 -1.4
 f_10_12 tq_12_2 -1.3
 f_10_12 tq_12_3 -1.8
 f_10_12 tq_12_4 -1.4
 f_10_13 cost -30
 f_10_13 dem_13 1
 f_10_13 bal_10 -1
 f_10_13 tq_13_1 -1.3
 f_10_13 tq_13_2 -1.3
 f_10_13 tq_13_3 -1.9
 f_10_13 tq_13_4 -1.9
 f_10_14 cost -6
 f_10_14 dem_14 1
 f_10_14 bal_10 -1
 f_10_14 tq_14_1 -1.2
 f_10_14 tq_14_2 -1.1
 f_10_14 tq_14_3 -1.7
 f_10_14 tq_14_4 -1.6
 f_10_15 cost -10
 f_10_15 dem_15 1
 f_10_15 bal_10 -1
 f_10_15 tq_15_1 -1.6
 f_10_15 tq_15_2 -1.9
 f_10_15 tq_15_3 -2
 f_10_15 tq_15_4 -2.5
 p_9_1 cost 0
 p_9_2 cost 0
 p_9_3 cost 0
 p_9_4 cost 0
 p_10_1 cost 0
 p_10_2 cost 0
 p_10_3 cost 0
 p_10_4 cost 0
RHS
 rhs src_1 85
 rhs src_2 85
 rhs src_3 85
 rhs src_4 85
 rhs src_5 85
 rhs src_6 85
 rhs src_7 85
 rhs src_8 85
 rhs dem_11 15
 rhs dem_12 25
 rhs dem_13 10
 rhs dem_14 20
 rhs dem_15 15
 rhs cap_9 85
 rhs cap_10 85
BOUNDS
 UP bnd f_1_9 85
 UP bnd f_2_9 85
 UP bnd f_3_9 85
 UP bnd f_4_9 85
 UP bnd f_5_10 85
 UP bnd f_6_10 85
 UP bnd f_7_10 85
 UP bnd f_8_10 85
 UP bnd f_9_11 15
 UP bnd f_9_12 25
 UP bnd f_9_13 10
 UP bnd f_9_14 20
 UP bnd f_9_15 15
 UP bnd f_10_11 15
 UP bnd f_10_12 25
 UP bnd f_10_13 10
 UP bnd f_10_14 20
 UP bnd f_10_15 15
 LO bnd p_9_1 0.5
 UP bnd p_9_1 1.5
 LO bnd p_9_2 1.2
 UP bnd p_9_2 1.9
 LO bnd p_9_3 1.3
 UP bnd p_9_3 1.7
 LO bnd p_9_4 1
 UP bnd p_9_4 1.6
 LO bnd p_10_1 1.2
 UP bnd p_10_1 1.6
 LO bnd p_10_2 1.1
 UP bnd p_10_2 1.8
 LO bnd p_10_3 1.2
 UP bnd p_10_3 1.6
 LO bnd p_10_4 1.5
 UP bnd p_10_4 2
QCMATRIX pq_9_1
 f_9_11 p_9_1 -0.5
 p_9_1 f_9_11 -0.5
 f_9_12 p_9_1 -0.5
 p_9_1 f_9_12 -0.5
 f_9_13 p_9_1 -0.5
 p_9_1 f_9_13 -0.5
 f_9_14 p_9_1 -0.5
 p_9_1 f_9_14 -0.5
 f_9_15 p_9_1 -0.5
 p_9_1 f_9_15 -0.5
QCMATRIX pq_9_2
 f_9_11 p_9_2 -0.5
 p_9_2 f_9_11 -0.5
 f_9_12 p_9_2 -0.5
 p_9_2 f_9_12 -0.5
 f_9_13 p_9_2 -0.5
 p_9_2 f_9_13 -0.5
 f_9_14 p_9_2 -0.5
 p_9_2 f_9_14 -0.5
 f_9_15 p_9_2 -0.5
 p_9_2 f_9_15 -0.5
QCMATRIX pq_9_3
 f_9_11 p_9_3 -0.5
 p_9_3 f_9_11 -0.5
 f_9_12 p_9_3 -0.5
 p_9_3 f_9_12 -0.5
 f_9_13 p_9_3 -0.5
 p_9_3 f_9_13 -0.5
 f_9_14 p_9_3 -0.5
 p_9_3 f_9_14 -0.5
 f_9_15 p_9_3 -0.5
 p_9_3 f_9_15 -0.5
QCMATRIX pq_9_4
 f_9_11 p_9_4 -0.5
 p_9_4 f_9_11 -0.5
 f_9_12 p_9_4 -0.5
 p_9_4 f_9_12 -0.5
 f_9_13 p_9_4 -0.5
 p_9_4 f_9_13 -0.5
 f_9_14 p_9_4 -0.5
 p_9_4 f_9_14 -0.5
 f_9_15 p_9_4 -0.5
 p_9_4 f_9_15 -0.5
QCMATRIX pq_10_1
 f_10_11 p_10_1 -0.5
 p_10_1 f_10_11 -0.5
 f_10_12 p_10_1 -0.5
 p_10_1 f_10_12 -0.5
 f_10_13 p_10_1 -0.5
 p_10_1 f_10_13 -0.5
 f_10_14 p_10_1 -0.5
 p_10_1 f_10_14 -0.5
 f_10_15 p_10_1 -0.5
 p_10_1 f_10_15 -0.5
QCMATRIX pq_10_2
 f_10_11 p_10_2 -0.5
 p_10_2 f_10_11 -0.5
 f_10_12 p_10_2 -0.5
 p_10_2 f_10_12 -0.5
 f_10_13 p_10_2 -0.5
 p_10_2 f_10_13 -0.5
 f_10_14 p_10_2 -0.5
 p_10_2 f_10_14 -0.5
 f_10_15 p_10_2 -0.5
 p_10_2 f_10_15 -0.5
QCMATRIX pq_10_3
 f_10_11 p_10_3 -0.5
 p_10_3 f_10_11 -0.5
 f_10_12 p_10_3 -0.5
 p_10_3 f_10_12 -0.5
 f_10_13 p_10_3 -0.5
 p_10_3 f_10_13 -0.5
 f_10_14 p_10_3 -0.5
 p_10_3 f_10_14 -0.5
 f_10_15 p_10_3 -0.5
 p_10_3 f_10_15 -0.5
QCMATRIX pq_10_4
 f_10_11 p_10_4 -0.5
 p_10_4 f_10_11 -0.5
 f_10_12 p_10_4 -0.5
 p_10_4 f_10_12 -0.5
 f_10_13 p_10_4 -0.5
 p_10_4 f_10_13 -0.5
 f_10_14 p_10_4 -0.5
 p_10_4 f_10_14 -0.5
 f_10_15 p_10_4 -0.5
 p_10_4 f_10_15 -0.5
QCMATRIX tq_11_1
 f_9_11 p_9_1 0.5
 p_9_1 f_9_11 0.5
 f_10_11 p_10_1 0.5
 p_10_1 f_10_11 0.5
QCMATRIX tq_11_2
 f_9_11 p_9_2 0.5
 p_9_2 f_9_11 0.5
 f_10_11 p_10_2 0.5
 p_10_2 f_10_11 0.5
QCMATRIX tq_11_3
 f_9_11 p_9_3 0.5
 p_9_3 f_9_11 0.5
 f_10_11 p_10_3 0.5
 p_10_3 f_10_11 0.5
QCMATRIX tq_11_4
 f_9_11 p_9_4 0.5
 p_9_4 f_9_11 0.5
 f_10_11 p_10_4 0.5
 p_10_4 f_10_11 0.5
QCMATRIX tq_12_1
 f_9_12 p_9_1 0.5
 p_9_1 f_9_12 0.5
 f_10_12 p_10_1 0.5
 p_10_1 f_10_12 0.5
QCMATRIX tq_12_2
 f_9_12 p_9_2 0.5
 p_9_2 f_9_12 0.5
 f_10_12 p_10_2 0.5
 p_10_2 f_10_12 0.5
QCMATRIX tq_12_3
 f_9_12 p_9_3 0.5
 p_9_3 f_9_12 0.5
 f_10_12 p_10_3 0.5
 p_10_3 f_10_12 0.5
QCMATRIX tq_12_4
 f_9_12 p_9_4 0.5
 p_9_4 f_9_12 0.5
 f_10_12 p_10_4 0.5
 p_10_4 f_10_12 0.5
QCMATRIX tq_13_1
 f_9_13 p_9_1 0.5
 p_9_1 f_9_13 0.5
 f_10_13 p_10_1 0.5
 p_10_1 f_10_13 0.5
QCMATRIX tq_13_2
 f_9_13 p_9_2 0.5
 p_9_2 f_9_13 0.5
 f_10_13 p_10_2 0.5
 p_10_2 f_10_13 0.5
QCMATRIX tq_13_3
 f_9_13 p_9_3 0.5
 p_9_3 f_9_13 0.5
 f_10_13 p_10_3 0.5
 p_10_3 f_10_13 0.5
QCMATRIX tq_13_4
 f_9_13 p_9_4 0.5
 p_9_4 f_9_13 0.5
 f_10_13 p_10_4 0.5
 p_10_4 f_10_13 0.5
QCMATRIX tq_14_1
 f_9_14 p_9_1 0.5
 p_9_1 f_9_14 0.5
 f_10_14 p_10_1 0.5
 p_10_1 f_10_14 0.5
QCMATRIX tq_14_2
 f_9_14 p_9_2 0.5
 p_9_2 f_9_14 0.5
 f_10_14 p_10_2 0.5
 p_10_2 f_10_14 0.5
QCMATRIX tq_14_3
 f_9_14 p_9_3 0.5
 p_9_3 f_9_14 0.5
 f_10_14 p_10_3 0.5
 p_10_3 f_10_14 0.5
QCMATRIX tq_14_4
 f_9_14 p_9_4 0.5
 p_9_4 f_9_14 0.5
 f_10_14 p_10_4 0.5
 p_10_4 f_10_14 0.5
QCMATRIX tq_15_1
 f_9_15 p_9_1 0.5
 p_9_1 f_9_15 0.5
 f_10_15 p_10_1 0.5
 p_10_1 f_10_15 0.5
QCMATRIX tq_15_2
 f_9_15 p_9_2 0.5
 p_9_2 f_9_15 0.5
 f_10_15 p_10_2 0.5
 p_10_2 f_10_15 0.5
QCMATRIX tq_15_3
 f_9_15 p_9_3 0.5
 p_9_3 f_9_15 0.5
 f_10_15 p_10_3 0.5
 p_10_3 f_10_15 0.5
QCMATRIX tq_15_4
 f_9_15 p_9_4 0.5
 p_9_4 f_9_15 0.5
 f_10_15 p_10_4 0.5
 p_10_4 f_10_15 0.5
ENDATA
