* SANKHYA pooling instance adhya1, P-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/adhya1.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Adhya1.gms
* (sha256 e1112775090613bd1882c5c3e6dfe166d5a837de0ae31cc3ea7f0272128de471).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* P-formulation (Haverly 1978; Tawarmalani and Sahinidis 2002, ch. 9)
NAME adhya1_p
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L src_5
 L dem_8
 L dem_9
 L dem_10
 L dem_11
 E bal_6
 L cap_6
 E pq_6_1
 E pq_6_2
 E pq_6_3
 E pq_6_4
 E bal_7
 L cap_7
 E pq_7_1
 E pq_7_2
 E pq_7_3
 E pq_7_4
 L tq_8_1
 L tq_8_2
 L tq_8_3
 L tq_8_4
 L tq_9_1
 L tq_9_2
 L tq_9_3
 L tq_9_4
 L tq_10_1
 L tq_10_2
 L tq_10_3
 L tq_10_4
 L tq_11_1
 L tq_11_2
 L tq_11_3
 L tq_11_4
COLUMNS
 f_1_6 cost 7
 f_1_6 src_1 1
 f_1_6 bal_6 1
 f_1_6 cap_6 1
 f_1_6 pq_6_1 1
 f_1_6 pq_6_2 6
 f_1_6 pq_6_3 4
 f_1_6 pq_6_4 0.5
 f_2_6 cost 3
 f_2_6 src_2 1
 f_2_6 bal_6 1
 f_2_6 cap_6 1
 f_2_6 pq_6_1 4
 f_2_6 pq_6_2 1
 f_2_6 pq_6_3 3
 f_2_6 pq_6_4 2
 f_3_7 cost 2
 f_3_7 src_3 1
 f_3_7 bal_7 1
 f_3_7 cap_7 1
 f_3_7 pq_7_1 4
 f_3_7 pq_7_2 5.5
 f_3_7 pq_7_3 3
 f_3_7 pq_7_4 0.9
 f_4_7 cost 10
 f_4_7 src_4 1
 f_4_7 bal_7 1
 f_4_7 cap_7 1
 f_4_7 pq_7_1 3
 f_4_7 pq_7_2 3
 f_4_7 pq_7_3 3
 f_4_7 pq_7_4 1
 f_5_7 cost 5
 f_5_7 src_5 1
 f_5_7 bal_7 1
 f_5_7 cap_7 1
 f_5_7 pq_7_1 1
 f_5_7 pq_7_2 2.7
 f_5_7 pq_7_3 4
 f_5_7 pq_7_4 1.6
 f_6_8 cost -16
 f_6_8 dem_8 1
 f_6_8 bal_6 -1
 f_6_8 tq_8_1 -3
 f_6_8 tq_8_2 -3
 f_6_8 tq_8_3 -3.25
 f_6_8 tq_8_4 -0.75
 f_6_9 cost -25
 f_6_9 dem_9 1
 f_6_9 bal_6 -1
 f_6_9 tq_9_1 -4
 f_6_9 tq_9_2 -2.5
 f_6_9 tq_9_3 -3.5
 f_6_9 tq_9_4 -1.5
 f_6_10 cost -15
 f_6_10 dem_10 1
 f_6_10 bal_6 -1
 f_6_10 tq_10_1 -1.5
 f_6_10 tq_10_2 -5.5
 f_6_10 tq_10_3 -3.9
 f_6_10 tq_10_4 -0.8
 f_6_11 cost -10
 f_6_11 dem_11 1
 f_6_11 bal_6 -1
 f_6_11 tq_11_1 -3
 f_6_11 tq_11_2 -4
 f_6_11 tq_11_3 -4
 f_6_11 tq_11_4 -1.8
 f_7_8 cost -16
 f_7_8 dem_8 1
 f_7_8 bal_7 -1
 f_7_8 tq_8_1 -3
 f_7_8 tq_8_2 -3
 f_7_8 tq_8_3 -3.25
 f_7_8 tq_8_4 -0.75
 f_7_9 cost -25
 f_7_9 dem_9 1
 f_7_9 bal_7 -1
 f_7_9 tq_9_1 -4
 f_7_9 tq_9_2 -2.5
 f_7_9 tq_9_3 -3.5
 f_7_9 tq_9_4 -1.5
 f_7_10 cost -15
 f_7_10 dem_10 1
 f_7_10 bal_7 -1
 f_7_10 tq_10_1 -1.5
 f_7_10 tq_10_2 -5.5
 f_7_10 tq_10_3 -3.9
 f_7_10 tq_10_4 -0.8
 f_7_11 cost -10
 f_7_11 dem_11 1
 f_7_11 bal_7 -1
 f_7_11 tq_11_1 -3
 f_7_11 tq_11_2 -4
 f_7_11 tq_11_3 -4
 f_7_11 tq_11_4 -1.8
 p_6_1 cost 0
 p_6_2 cost 0
 p_6_3 cost 0
 p_6_4 cost 0
 p_7_1 cost 0
 p_7_2 cost 0
 p_7_3 cost 0
 p_7_4 cost 0
RHS
 rhs src_1 75
 rhs src_2 75
 rhs src_3 75
 rhs src_4 75
 rhs src_5 75
 rhs dem_8 10
 rhs dem_9 25
 rhs dem_10 30
 rhs dem_11 10
 rhs cap_6 75
 rhs cap_7 75
BOUNDS
 UP bnd f_1_6 75
 UP bnd f_2_6 75
 UP bnd f_3_7 75
 UP bnd f_4_7 75
 UP bnd f_5_7 75
 UP bnd f_6_8 10
 UP bnd f_6_9 25
 UP bnd f_6_10 30
 UP bnd f_6_11 10
 UP bnd f_7_8 10
 UP bnd f_7_9 25
 UP bnd f_7_10 30
 UP bnd f_7_11 10
 LO bnd p_6_1 1
 UP bnd p_6_1 4
 LO bnd p_6_2 1
 UP bnd p_6_2 6
 LO bnd p_6_3 3
 UP bnd p_6_3 4
 LO bnd p_6_4 0.5
 UP bnd p_6_4 2
 LO bnd p_7_1 1
 UP bnd p_7_1 4
 LO bnd p_7_2 2.7
 UP bnd p_7_2 5.5
 LO bnd p_7_3 3
 UP bnd p_7_3 4
 LO bnd p_7_4 0.9
 UP bnd p_7_4 1.6
QCMATRIX pq_6_1
 f_6_8 p_6_1 -0.5
 p_6_1 f_6_8 -0.5
 f_6_9 p_6_1 -0.5
 p_6_1 f_6_9 -0.5
 f_6_10 p_6_1 -0.5
 p_6_1 f_6_10 -0.5
 f_6_11 p_6_1 -0.5
 p_6_1 f_6_11 -0.5
QCMATRIX pq_6_2
 f_6_8 p_6_2 -0.5
 p_6_2 f_6_8 -0.5
 f_6_9 p_6_2 -0.5
 p_6_2 f_6_9 -0.5
 f_6_10 p_6_2 -0.5
 p_6_2 f_6_10 -0.5
 f_6_11 p_6_2 -0.5
 p_6_2 f_6_11 -0.5
QCMATRIX pq_6_3
 f_6_8 p_6_3 -0.5
 p_6_3 f_6_8 -0.5
 f_6_9 p_6_3 -0.5
 p_6_3 f_6_9 -0.5
 f_6_10 p_6_3 -0.5
 p_6_3 f_6_10 -0.5
 f_6_11 p_6_3 -0.5
 p_6_3 f_6_11 -0.5
QCMATRIX pq_6_4
 f_6_8 p_6_4 -0.5
 p_6_4 f_6_8 -0.5
 f_6_9 p_6_4 -0.5
 p_6_4 f_6_9 -0.5
 f_6_10 p_6_4 -0.5
 p_6_4 f_6_10 -0.5
 f_6_11 p_6_4 -0.5
 p_6_4 f_6_11 -0.5
QCMATRIX pq_7_1
 f_7_8 p_7_1 -0.5
 p_7_1 f_7_8 -0.5
 f_7_9 p_7_1 -0.5
 p_7_1 f_7_9 -0.5
 f_7_10 p_7_1 -0.5
 p_7_1 f_7_10 -0.5
 f_7_11 p_7_1 -0.5
 p_7_1 f_7_11 -0.5
QCMATRIX pq_7_2
 f_7_8 p_7_2 -0.5
 p_7_2 f_7_8 -0.5
 f_7_9 p_7_2 -0.5
 p_7_2 f_7_9 -0.5
 f_7_10 p_7_2 -0.5
 p_7_2 f_7_10 -0.5
 f_7_11 p_7_2 -0.5
 p_7_2 f_7_11 -0.5
QCMATRIX pq_7_3
 f_7_8 p_7_3 -0.5
 p_7_3 f_7_8 -0.5
 f_7_9 p_7_3 -0.5
 p_7_3 f_7_9 -0.5
 f_7_10 p_7_3 -0.5
 p_7_3 f_7_10 -0.5
 f_7_11 p_7_3 -0.5
 p_7_3 f_7_11 -0.5
QCMATRIX pq_7_4
 f_7_8 p_7_4 -0.5
 p_7_4 f_7_8 -0.5
 f_7_9 p_7_4 -0.5
 p_7_4 f_7_9 -0.5
 f_7_10 p_7_4 -0.5
 p_7_4 f_7_10 -0.5
 f_7_11 p_7_4 -0.5
 p_7_4 f_7_11 -0.5
QCMATRIX tq_8_1
 f_6_8 p_6_1 0.5
 p_6_1 f_6_8 0.5
 f_7_8 p_7_1 0.5
 p_7_1 f_7_8 0.5
QCMATRIX tq_8_2
 f_6_8 p_6_2 0.5
 p_6_2 f_6_8 0.5
 f_7_8 p_7_2 0.5
 p_7_2 f_7_8 0.5
QCMATRIX tq_8_3
 f_6_8 p_6_3 0.5
 p_6_3 f_6_8 0.5
 f_7_8 p_7_3 0.5
 p_7_3 f_7_8 0.5
QCMATRIX tq_8_4
 f_6_8 p_6_4 0.5
 p_6_4 f_6_8 0.5
 f_7_8 p_7_4 0.5
 p_7_4 f_7_8 0.5
QCMATRIX tq_9_1
 f_6_9 p_6_1 0.5
 p_6_1 f_6_9 0.5
 f_7_9 p_7_1 0.5
 p_7_1 f_7_9 0.5
QCMATRIX tq_9_2
 f_6_9 p_6_2 0.5
 p_6_2 f_6_9 0.5
 f_7_9 p_7_2 0.5
 p_7_2 f_7_9 0.5
QCMATRIX tq_9_3
 f_6_9 p_6_3 0.5
 p_6_3 f_6_9 0.5
 f_7_9 p_7_3 0.5
 p_7_3 f_7_9 0.5
QCMATRIX tq_9_4
 f_6_9 p_6_4 0.5
 p_6_4 f_6_9 0.5
 f_7_9 p_7_4 0.5
 p_7_4 f_7_9 0.5
QCMATRIX tq_10_1
 f_6_10 p_6_1 0.5
 p_6_1 f_6_10 0.5
 f_7_10 p_7_1 0.5
 p_7_1 f_7_10 0.5
QCMATRIX tq_10_2
 f_6_10 p_6_2 0.5
 p_6_2 f_6_10 0.5
 f_7_10 p_7_2 0.5
 p_7_2 f_7_10 0.5
QCMATRIX tq_10_3
 f_6_10 p_6_3 0.5
 p_6_3 f_6_10 0.5
 f_7_10 p_7_3 0.5
 p_7_3 f_7_10 0.5
QCMATRIX tq_10_4
 f_6_10 p_6_4 0.5
 p_6_4 f_6_10 0.5
 f_7_10 p_7_4 0.5
 p_7_4 f_7_10 0.5
QCMATRIX tq_11_1
 f_6_11 p_6_1 0.5
 p_6_1 f_6_11 0.5
 f_7_11 p_7_1 0.5
 p_7_1 f_7_11 0.5
QCMATRIX tq_11_2
 f_6_11 p_6_2 0.5
 p_6_2 f_6_11 0.5
 f_7_11 p_7_2 0.5
 p_7_2 f_7_11 0.5
QCMATRIX tq_11_3
 f_6_11 p_6_3 0.5
 p_6_3 f_6_11 0.5
 f_7_11 p_7_3 0.5
 p_7_3 f_7_11 0.5
QCMATRIX tq_11_4
 f_6_11 p_6_4 0.5
 p_6_4 f_6_11 0.5
 f_7_11 p_7_4 0.5
 p_7_4 f_7_11 0.5
ENDATA
