* SANKHYA pooling instance bental5, PQ-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/bental5.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Bental5.gms
* (sha256 2b4447361cd8d07852677e7491040779fa75da9192883d23a697dd2da89ebffc).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* PQ-formulation (Quesada and Grossmann 1995; Tawarmalani and Sahinidis 2002)
NAME bental5_pq
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L src_5
 L dem_9
 L dem_10
 L dem_11
 L dem_12
 L dem_13
 E sumq_6
 L cap_6
 E sumq_7
 L cap_7
 E sumq_8
 L cap_8
 L tq_9_1
 L tq_9_2
 L tq_10_1
 L tq_10_2
 L tq_11_1
 L tq_11_2
 L tq_12_1
 L tq_12_2
 L tq_13_1
 L tq_13_2
 E path_1_6_9
 E path_1_6_10
 E path_1_6_11
 E path_1_6_12
 E path_1_6_13
 E path_2_6_9
 E path_2_6_10
 E path_2_6_11
 E path_2_6_12
 E path_2_6_13
 E path_3_6_9
 E path_3_6_10
 E path_3_6_11
 E path_3_6_12
 E path_3_6_13
 E path_4_6_9
 E path_4_6_10
 E path_4_6_11
 E path_4_6_12
 E path_4_6_13
 E path_1_7_9
 E path_1_7_10
 E path_1_7_11
 E path_1_7_12
 E path_1_7_13
 E path_2_7_9
 E path_2_7_10
 E path_2_7_11
 E path_2_7_12
 E path_2_7_13
 E path_3_7_9
 E path_3_7_10
 E path_3_7_11
 E path_3_7_12
 E path_3_7_13
 E path_4_7_9
 E path_4_7_10
 E path_4_7_11
 E path_4_7_12
 E path_4_7_13
 E path_1_8_9
 E path_1_8_10
 E path_1_8_11
 E path_1_8_12
 E path_1_8_13
 E path_2_8_9
 E path_2_8_10
 E path_2_8_11
 E path_2_8_12
 E path_2_8_13
 E path_3_8_9
 E path_3_8_10
 E path_3_8_11
 E path_3_8_12
 E path_3_8_13
 E path_4_8_9
 E path_4_8_10
 E path_4_8_11
 E path_4_8_12
 E path_4_8_13
 E rlt_6_9
 E rlt_6_10
 E rlt_6_11
 E rlt_6_12
 E rlt_6_13
 L rltc_1_6
 L rltc_2_6
 L rltc_3_6
 L rltc_4_6
 E rlt_7_9
 E rlt_7_10
 E rlt_7_11
 E rlt_7_12
 E rlt_7_13
 L rltc_1_7
 L rltc_2_7
 L rltc_3_7
 L rltc_4_7
 E rlt_8_9
 E rlt_8_10
 E rlt_8_11
 E rlt_8_12
 E rlt_8_13
 L rltc_1_8
 L rltc_2_8
 L rltc_3_8
 L rltc_4_8
COLUMNS
 q_1_6 sumq_6 1
 q_1_6 rltc_1_6 -600
 q_2_6 sumq_6 1
 q_2_6 rltc_2_6 -600
 q_3_6 sumq_6 1
 q_3_6 rltc_3_6 -600
 q_4_6 sumq_6 1
 q_4_6 rltc_4_6 -600
 q_1_7 sumq_7 1
 q_1_7 rltc_1_7 -600
 q_2_7 sumq_7 1
 q_2_7 rltc_2_7 -600
 q_3_7 sumq_7 1
 q_3_7 rltc_3_7 -600
 q_4_7 sumq_7 1
 q_4_7 rltc_4_7 -600
 q_1_8 sumq_8 1
 q_1_8 rltc_1_8 -600
 q_2_8 sumq_8 1
 q_2_8 rltc_2_8 -600
 q_3_8 sumq_8 1
 q_3_8 rltc_3_8 -600
 q_4_8 sumq_8 1
 q_4_8 rltc_4_8 -600
 f_5_9 cost -8
 f_5_9 src_5 1
 f_5_9 dem_9 1
 f_5_9 tq_9_1 -0.5
 f_5_9 tq_9_2 0.5
 f_5_10 cost -5
 f_5_10 src_5 1
 f_5_10 dem_10 1
 f_5_10 tq_10_1 0.5
 f_5_11 cost -9
 f_5_11 src_5 1
 f_5_11 dem_11 1
 f_5_11 tq_11_2 -0.10000000000000009
 f_5_12 cost -6
 f_5_12 src_5 1
 f_5_12 dem_12 1
 f_5_12 tq_12_2 0.5
 f_5_13 cost -4
 f_5_13 src_5 1
 f_5_13 dem_13 1
 f_5_13 tq_13_2 0.5
 f_6_9 cost -18
 f_6_9 dem_9 1
 f_6_9 cap_6 1
 f_6_9 tq_9_1 -2.5
 f_6_9 tq_9_2 -2
 f_6_9 rlt_6_9 -1
 f_6_10 cost -15
 f_6_10 dem_10 1
 f_6_10 cap_6 1
 f_6_10 tq_10_1 -1.5
 f_6_10 tq_10_2 -2.5
 f_6_10 rlt_6_10 -1
 f_6_11 cost -19
 f_6_11 dem_11 1
 f_6_11 cap_6 1
 f_6_11 tq_11_1 -2
 f_6_11 tq_11_2 -2.6
 f_6_11 rlt_6_11 -1
 f_6_12 cost -16
 f_6_12 dem_12 1
 f_6_12 cap_6 1
 f_6_12 tq_12_1 -2
 f_6_12 tq_12_2 -2
 f_6_12 rlt_6_12 -1
 f_6_13 cost -14
 f_6_13 dem_13 1
 f_6_13 cap_6 1
 f_6_13 tq_13_1 -2
 f_6_13 tq_13_2 -2
 f_6_13 rlt_6_13 -1
 f_7_9 cost -18
 f_7_9 dem_9 1
 f_7_9 cap_7 1
 f_7_9 tq_9_1 -2.5
 f_7_9 tq_9_2 -2
 f_7_9 rlt_7_9 -1
 f_7_10 cost -15
 f_7_10 dem_10 1
 f_7_10 cap_7 1
 f_7_10 tq_10_1 -1.5
 f_7_10 tq_10_2 -2.5
 f_7_10 rlt_7_10 -1
 f_7_11 cost -19
 f_7_11 dem_11 1
 f_7_11 cap_7 1
 f_7_11 tq_11_1 -2
 f_7_11 tq_11_2 -2.6
 f_7_11 rlt_7_11 -1
 f_7_12 cost -16
 f_7_12 dem_12 1
 f_7_12 cap_7 1
 f_7_12 tq_12_1 -2
 f_7_12 tq_12_2 -2
 f_7_12 rlt_7_12 -1
 f_7_13 cost -14
 f_7_13 dem_13 1
 f_7_13 cap_7 1
 f_7_13 tq_13_1 -2
 f_7_13 tq_13_2 -2
 f_7_13 rlt_7_13 -1
 f_8_9 cost -18
 f_8_9 dem_9 1
 f_8_9 cap_8 1
 f_8_9 tq_9_1 -2.5
 f_8_9 tq_9_2 -2
 f_8_9 rlt_8_9 -1
 f_8_10 cost -15
 f_8_10 dem_10 1
 f_8_10 cap_8 1
 f_8_10 tq_10_1 -1.5
 f_8_10 tq_10_2 -2.5
 f_8_10 rlt_8_10 -1
 f_8_11 cost -19
 f_8_11 dem_11 1
 f_8_11 cap_8 1
 f_8_11 tq_11_1 -2
 f_8_11 tq_11_2 -2.6
 f_8_11 rlt_8_11 -1
 f_8_12 cost -16
 f_8_12 dem_12 1
 f_8_12 cap_8 1
 f_8_12 tq_12_1 -2
 f_8_12 tq_12_2 -2
 f_8_12 rlt_8_12 -1
 f_8_13 cost -14
 f_8_13 dem_13 1
 f_8_13 cap_8 1
 f_8_13 tq_13_1 -2
 f_8_13 tq_13_2 -2
 f_8_13 rlt_8_13 -1
 v_1_6_9 cost 6
 v_1_6_9 src_1 1
 v_1_6_9 tq_9_1 3
 v_1_6_9 tq_9_2 1
 v_1_6_9 path_1_6_9 1
 v_1_6_9 rlt_6_9 1
 v_1_6_9 rltc_1_6 1
 v_1_6_10 cost 6
 v_1_6_10 src_1 1
 v_1_6_10 tq_10_1 3
 v_1_6_10 tq_10_2 1
 v_1_6_10 path_1_6_10 1
 v_1_6_10 rlt_6_10 1
 v_1_6_10 rltc_1_6 1
 v_1_6_11 cost 6
 v_1_6_11 src_1 1
 v_1_6_11 tq_11_1 3
 v_1_6_11 tq_11_2 1
 v_1_6_11 path_1_6_11 1
 v_1_6_11 rlt_6_11 1
 v_1_6_11 rltc_1_6 1
 v_1_6_12 cost 6
 v_1_6_12 src_1 1
 v_1_6_12 tq_12_1 3
 v_1_6_12 tq_12_2 1
 v_1_6_12 path_1_6_12 1
 v_1_6_12 rlt_6_12 1
 v_1_6_12 rltc_1_6 1
 v_1_6_13 cost 6
 v_1_6_13 src_1 1
 v_1_6_13 tq_13_1 3
 v_1_6_13 tq_13_2 1
 v_1_6_13 path_1_6_13 1
 v_1_6_13 rlt_6_13 1
 v_1_6_13 rltc_1_6 1
 v_2_6_9 cost 16
 v_2_6_9 src_2 1
 v_2_6_9 tq_9_1 1
 v_2_6_9 tq_9_2 3
 v_2_6_9 path_2_6_9 1
 v_2_6_9 rlt_6_9 1
 v_2_6_9 rltc_2_6 1
 v_2_6_10 cost 16
 v_2_6_10 src_2 1
 v_2_6_10 tq_10_1 1
 v_2_6_10 tq_10_2 3
 v_2_6_10 path_2_6_10 1
 v_2_6_10 rlt_6_10 1
 v_2_6_10 rltc_2_6 1
 v_2_6_11 cost 16
 v_2_6_11 src_2 1
 v_2_6_11 tq_11_1 1
 v_2_6_11 tq_11_2 3
 v_2_6_11 path_2_6_11 1
 v_2_6_11 rlt_6_11 1
 v_2_6_11 rltc_2_6 1
 v_2_6_12 cost 16
 v_2_6_12 src_2 1
 v_2_6_12 tq_12_1 1
 v_2_6_12 tq_12_2 3
 v_2_6_12 path_2_6_12 1
 v_2_6_12 rlt_6_12 1
 v_2_6_12 rltc_2_6 1
 v_2_6_13 cost 16
 v_2_6_13 src_2 1
 v_2_6_13 tq_13_1 1
 v_2_6_13 tq_13_2 3
 v_2_6_13 path_2_6_13 1
 v_2_6_13 rlt_6_13 1
 v_2_6_13 rltc_2_6 1
 v_3_6_9 cost 15
 v_3_6_9 src_3 1
 v_3_6_9 tq_9_1 1
 v_3_6_9 tq_9_2 2.5
 v_3_6_9 path_3_6_9 1
 v_3_6_9 rlt_6_9 1
 v_3_6_9 rltc_3_6 1
 v_3_6_10 cost 15
 v_3_6_10 src_3 1
 v_3_6_10 tq_10_1 1
 v_3_6_10 tq_10_2 2.5
 v_3_6_10 path_3_6_10 1
 v_3_6_10 rlt_6_10 1
 v_3_6_10 rltc_3_6 1
 v_3_6_11 cost 15
 v_3_6_11 src_3 1
 v_3_6_11 tq_11_1 1
 v_3_6_11 tq_11_2 2.5
 v_3_6_11 path_3_6_11 1
 v_3_6_11 rlt_6_11 1
 v_3_6_11 rltc_3_6 1
 v_3_6_12 cost 15
 v_3_6_12 src_3 1
 v_3_6_12 tq_12_1 1
 v_3_6_12 tq_12_2 2.5
 v_3_6_12 path_3_6_12 1
 v_3_6_12 rlt_6_12 1
 v_3_6_12 rltc_3_6 1
 v_3_6_13 cost 15
 v_3_6_13 src_3 1
 v_3_6_13 tq_13_1 1
 v_3_6_13 tq_13_2 2.5
 v_3_6_13 path_3_6_13 1
 v_3_6_13 rlt_6_13 1
 v_3_6_13 rltc_3_6 1
 v_4_6_9 cost 12
 v_4_6_9 src_4 1
 v_4_6_9 tq_9_1 1.5
 v_4_6_9 tq_9_2 2.5
 v_4_6_9 path_4_6_9 1
 v_4_6_9 rlt_6_9 1
 v_4_6_9 rltc_4_6 1
 v_4_6_10 cost 12
 v_4_6_10 src_4 1
 v_4_6_10 tq_10_1 1.5
 v_4_6_10 tq_10_2 2.5
 v_4_6_10 path_4_6_10 1
 v_4_6_10 rlt_6_10 1
 v_4_6_10 rltc_4_6 1
 v_4_6_11 cost 12
 v_4_6_11 src_4 1
 v_4_6_11 tq_11_1 1.5
 v_4_6_11 tq_11_2 2.5
 v_4_6_11 path_4_6_11 1
 v_4_6_11 rlt_6_11 1
 v_4_6_11 rltc_4_6 1
 v_4_6_12 cost 12
 v_4_6_12 src_4 1
 v_4_6_12 tq_12_1 1.5
 v_4_6_12 tq_12_2 2.5
 v_4_6_12 path_4_6_12 1
 v_4_6_12 rlt_6_12 1
 v_4_6_12 rltc_4_6 1
 v_4_6_13 cost 12
 v_4_6_13 src_4 1
 v_4_6_13 tq_13_1 1.5
 v_4_6_13 tq_13_2 2.5
 v_4_6_13 path_4_6_13 1
 v_4_6_13 rlt_6_13 1
 v_4_6_13 rltc_4_6 1
 v_1_7_9 cost 6
 v_1_7_9 src_1 1
 v_1_7_9 tq_9_1 3
 v_1_7_9 tq_9_2 1
 v_1_7_9 path_1_7_9 1
 v_1_7_9 rlt_7_9 1
 v_1_7_9 rltc_1_7 1
 v_1_7_10 cost 6
 v_1_7_10 src_1 1
 v_1_7_10 tq_10_1 3
 v_1_7_10 tq_10_2 1
 v_1_7_10 path_1_7_10 1
 v_1_7_10 rlt_7_10 1
 v_1_7_10 rltc_1_7 1
 v_1_7_11 cost 6
 v_1_7_11 src_1 1
 v_1_7_11 tq_11_1 3
 v_1_7_11 tq_11_2 1
 v_1_7_11 path_1_7_11 1
 v_1_7_11 rlt_7_11 1
 v_1_7_11 rltc_1_7 1
 v_1_7_12 cost 6
 v_1_7_12 src_1 1
 v_1_7_12 tq_12_1 3
 v_1_7_12 tq_12_2 1
 v_1_7_12 path_1_7_12 1
 v_1_7_12 rlt_7_12 1
 v_1_7_12 rltc_1_7 1
 v_1_7_13 cost 6
 v_1_7_13 src_1 1
 v_1_7_13 tq_13_1 3
 v_1_7_13 tq_13_2 1
 v_1_7_13 path_1_7_13 1
 v_1_7_13 rlt_7_13 1
 v_1_7_13 rltc_1_7 1
 v_2_7_9 cost 16
 v_2_7_9 src_2 1
 v_2_7_9 tq_9_1 1
 v_2_7_9 tq_9_2 3
 v_2_7_9 path_2_7_9 1
 v_2_7_9 rlt_7_9 1
 v_2_7_9 rltc_2_7 1
 v_2_7_10 cost 16
 v_2_7_10 src_2 1
 v_2_7_10 tq_10_1 1
 v_2_7_10 tq_10_2 3
 v_2_7_10 path_2_7_10 1
 v_2_7_10 rlt_7_10 1
 v_2_7_10 rltc_2_7 1
 v_2_7_11 cost 16
 v_2_7_11 src_2 1
 v_2_7_11 tq_11_1 1
 v_2_7_11 tq_11_2 3
 v_2_7_11 path_2_7_11 1
 v_2_7_11 rlt_7_11 1
 v_2_7_11 rltc_2_7 1
 v_2_7_12 cost 16
 v_2_7_12 src_2 1
 v_2_7_12 tq_12_1 1
 v_2_7_12 tq_12_2 3
 v_2_7_12 path_2_7_12 1
 v_2_7_12 rlt_7_12 1
 v_2_7_12 rltc_2_7 1
 v_2_7_13 cost 16
 v_2_7_13 src_2 1
 v_2_7_13 tq_13_1 1
 v_2_7_13 tq_13_2 3
 v_2_7_13 path_2_7_13 1
 v_2_7_13 rlt_7_13 1
 v_2_7_13 rltc_2_7 1
 v_3_7_9 cost 15
 v_3_7_9 src_3 1
 v_3_7_9 tq_9_1 1
 v_3_7_9 tq_9_2 2.5
 v_3_7_9 path_3_7_9 1
 v_3_7_9 rlt_7_9 1
 v_3_7_9 rltc_3_7 1
 v_3_7_10 cost 15
 v_3_7_10 src_3 1
 v_3_7_10 tq_10_1 1
 v_3_7_10 tq_10_2 2.5
 v_3_7_10 path_3_7_10 1
 v_3_7_10 rlt_7_10 1
 v_3_7_10 rltc_3_7 1
 v_3_7_11 cost 15
 v_3_7_11 src_3 1
 v_3_7_11 tq_11_1 1
 v_3_7_11 tq_11_2 2.5
 v_3_7_11 path_3_7_11 1
 v_3_7_11 rlt_7_11 1
 v_3_7_11 rltc_3_7 1
 v_3_7_12 cost 15
 v_3_7_12 src_3 1
 v_3_7_12 tq_12_1 1
 v_3_7_12 tq_12_2 2.5
 v_3_7_12 path_3_7_12 1
 v_3_7_12 rlt_7_12 1
 v_3_7_12 rltc_3_7 1
 v_3_7_13 cost 15
 v_3_7_13 src_3 1
 v_3_7_13 tq_13_1 1
 v_3_7_13 tq_13_2 2.5
 v_3_7_13 path_3_7_13 1
 v_3_7_13 rlt_7_13 1
 v_3_7_13 rltc_3_7 1
 v_4_7_9 cost 12
 v_4_7_9 src_4 1
 v_4_7_9 tq_9_1 1.5
 v_4_7_9 tq_9_2 2.5
 v_4_7_9 path_4_7_9 1
 v_4_7_9 rlt_7_9 1
 v_4_7_9 rltc_4_7 1
 v_4_7_10 cost 12
 v_4_7_10 src_4 1
 v_4_7_10 tq_10_1 1.5
 v_4_7_10 tq_10_2 2.5
 v_4_7_10 path_4_7_10 1
 v_4_7_10 rlt_7_10 1
 v_4_7_10 rltc_4_7 1
 v_4_7_11 cost 12
 v_4_7_11 src_4 1
 v_4_7_11 tq_11_1 1.5
 v_4_7_11 tq_11_2 2.5
 v_4_7_11 path_4_7_11 1
 v_4_7_11 rlt_7_11 1
 v_4_7_11 rltc_4_7 1
 v_4_7_12 cost 12
 v_4_7_12 src_4 1
 v_4_7_12 tq_12_1 1.5
 v_4_7_12 tq_12_2 2.5
 v_4_7_12 path_4_7_12 1
 v_4_7_12 rlt_7_12 1
 v_4_7_12 rltc_4_7 1
 v_4_7_13 cost 12
 v_4_7_13 src_4 1
 v_4_7_13 tq_13_1 1.5
 v_4_7_13 tq_13_2 2.5
 v_4_7_13 path_4_7_13 1
 v_4_7_13 rlt_7_13 1
 v_4_7_13 rltc_4_7 1
 v_1_8_9 cost 6
 v_1_8_9 src_1 1
 v_1_8_9 tq_9_1 3
 v_1_8_9 tq_9_2 1
 v_1_8_9 path_1_8_9 1
 v_1_8_9 rlt_8_9 1
 v_1_8_9 rltc_1_8 1
 v_1_8_10 cost 6
 v_1_8_10 src_1 1
 v_1_8_10 tq_10_1 3
 v_1_8_10 tq_10_2 1
 v_1_8_10 path_1_8_10 1
 v_1_8_10 rlt_8_10 1
 v_1_8_10 rltc_1_8 1
 v_1_8_11 cost 6
 v_1_8_11 src_1 1
 v_1_8_11 tq_11_1 3
 v_1_8_11 tq_11_2 1
 v_1_8_11 path_1_8_11 1
 v_1_8_11 rlt_8_11 1
 v_1_8_11 rltc_1_8 1
 v_1_8_12 cost 6
 v_1_8_12 src_1 1
 v_1_8_12 tq_12_1 3
 v_1_8_12 tq_12_2 1
 v_1_8_12 path_1_8_12 1
 v_1_8_12 rlt_8_12 1
 v_1_8_12 rltc_1_8 1
 v_1_8_13 cost 6
 v_1_8_13 src_1 1
 v_1_8_13 tq_13_1 3
 v_1_8_13 tq_13_2 1
 v_1_8_13 path_1_8_13 1
 v_1_8_13 rlt_8_13 1
 v_1_8_13 rltc_1_8 1
 v_2_8_9 cost 16
 v_2_8_9 src_2 1
 v_2_8_9 tq_9_1 1
 v_2_8_9 tq_9_2 3
 v_2_8_9 path_2_8_9 1
 v_2_8_9 rlt_8_9 1
 v_2_8_9 rltc_2_8 1
 v_2_8_10 cost 16
 v_2_8_10 src_2 1
 v_2_8_10 tq_10_1 1
 v_2_8_10 tq_10_2 3
 v_2_8_10 path_2_8_10 1
 v_2_8_10 rlt_8_10 1
 v_2_8_10 rltc_2_8 1
 v_2_8_11 cost 16
 v_2_8_11 src_2 1
 v_2_8_11 tq_11_1 1
 v_2_8_11 tq_11_2 3
 v_2_8_11 path_2_8_11 1
 v_2_8_11 rlt_8_11 1
 v_2_8_11 rltc_2_8 1
 v_2_8_12 cost 16
 v_2_8_12 src_2 1
 v_2_8_12 tq_12_1 1
 v_2_8_12 tq_12_2 3
 v_2_8_12 path_2_8_12 1
 v_2_8_12 rlt_8_12 1
 v_2_8_12 rltc_2_8 1
 v_2_8_13 cost 16
 v_2_8_13 src_2 1
 v_2_8_13 tq_13_1 1
 v_2_8_13 tq_13_2 3
 v_2_8_13 path_2_8_13 1
 v_2_8_13 rlt_8_13 1
 v_2_8_13 rltc_2_8 1
 v_3_8_9 cost 15
 v_3_8_9 src_3 1
 v_3_8_9 tq_9_1 1
 v_3_8_9 tq_9_2 2.5
 v_3_8_9 path_3_8_9 1
 v_3_8_9 rlt_8_9 1
 v_3_8_9 rltc_3_8 1
 v_3_8_10 cost 15
 v_3_8_10 src_3 1
 v_3_8_10 tq_10_1 1
 v_3_8_10 tq_10_2 2.5
 v_3_8_10 path_3_8_10 1
 v_3_8_10 rlt_8_10 1
 v_3_8_10 rltc_3_8 1
 v_3_8_11 cost 15
 v_3_8_11 src_3 1
 v_3_8_11 tq_11_1 1
 v_3_8_11 tq_11_2 2.5
 v_3_8_11 path_3_8_11 1
 v_3_8_11 rlt_8_11 1
 v_3_8_11 rltc_3_8 1
 v_3_8_12 cost 15
 v_3_8_12 src_3 1
 v_3_8_12 tq_12_1 1
 v_3_8_12 tq_12_2 2.5
 v_3_8_12 path_3_8_12 1
 v_3_8_12 rlt_8_12 1
 v_3_8_12 rltc_3_8 1
 v_3_8_13 cost 15
 v_3_8_13 src_3 1
 v_3_8_13 tq_13_1 1
 v_3_8_13 tq_13_2 2.5
 v_3_8_13 path_3_8_13 1
 v_3_8_13 rlt_8_13 1
 v_3_8_13 rltc_3_8 1
 v_4_8_9 cost 12
 v_4_8_9 src_4 1
 v_4_8_9 tq_9_1 1.5
 v_4_8_9 tq_9_2 2.5
 v_4_8_9 path_4_8_9 1
 v_4_8_9 rlt_8_9 1
 v_4_8_9 rltc_4_8 1
 v_4_8_10 cost 12
 v_4_8_10 src_4 1
 v_4_8_10 tq_10_1 1.5
 v_4_8_10 tq_10_2 2.5
 v_4_8_10 path_4_8_10 1
 v_4_8_10 rlt_8_10 1
 v_4_8_10 rltc_4_8 1
 v_4_8_11 cost 12
 v_4_8_11 src_4 1
 v_4_8_11 tq_11_1 1.5
 v_4_8_11 tq_11_2 2.5
 v_4_8_11 path_4_8_11 1
 v_4_8_11 rlt_8_11 1
 v_4_8_11 rltc_4_8 1
 v_4_8_12 cost 12
 v_4_8_12 src_4 1
 v_4_8_12 tq_12_1 1.5
 v_4_8_12 tq_12_2 2.5
 v_4_8_12 path_4_8_12 1
 v_4_8_12 rlt_8_12 1
 v_4_8_12 rltc_4_8 1
 v_4_8_13 cost 12
 v_4_8_13 src_4 1
 v_4_8_13 tq_13_1 1.5
 v_4_8_13 tq_13_2 2.5
 v_4_8_13 path_4_8_13 1
 v_4_8_13 rlt_8_13 1
 v_4_8_13 rltc_4_8 1
RHS
 rhs src_1 600
 rhs src_2 600
 rhs src_3 50
 rhs src_4 600
 rhs src_5 600
 rhs dem_9 100
 rhs dem_10 200
 rhs dem_11 100
 rhs dem_12 100
 rhs dem_13 100
 rhs sumq_6 1
 rhs cap_6 600
 rhs sumq_7 1
 rhs cap_7 600
 rhs sumq_8 1
 rhs cap_8 600
BOUNDS
 UP bnd q_1_6 1
 UP bnd q_2_6 1
 UP bnd q_3_6 1
 UP bnd q_4_6 1
 UP bnd q_1_7 1
 UP bnd q_2_7 1
 UP bnd q_3_7 1
 UP bnd q_4_7 1
 UP bnd q_1_8 1
 UP bnd q_2_8 1
 UP bnd q_3_8 1
 UP bnd q_4_8 1
 UP bnd f_5_9 100
 UP bnd f_5_10 200
 UP bnd f_5_11 100
 UP bnd f_5_12 100
 UP bnd f_5_13 100
 UP bnd f_6_9 100
 UP bnd f_6_10 200
 UP bnd f_6_11 100
 UP bnd f_6_12 100
 UP bnd f_6_13 100
 UP bnd f_7_9 100
 UP bnd f_7_10 200
 UP bnd f_7_11 100
 UP bnd f_7_12 100
 UP bnd f_7_13 100
 UP bnd f_8_9 100
 UP bnd f_8_10 200
 UP bnd f_8_11 100
 UP bnd f_8_12 100
 UP bnd f_8_13 100
 UP bnd v_1_6_9 100
 UP bnd v_1_6_10 200
 UP bnd v_1_6_11 100
 UP bnd v_1_6_12 100
 UP bnd v_1_6_13 100
 UP bnd v_2_6_9 100
 UP bnd v_2_6_10 200
 UP bnd v_2_6_11 100
 UP bnd v_2_6_12 100
 UP bnd v_2_6_13 100
 UP bnd v_3_6_9 50
 UP bnd v_3_6_10 50
 UP bnd v_3_6_11 50
 UP bnd v_3_6_12 50
 UP bnd v_3_6_13 50
 UP bnd v_4_6_9 100
 UP bnd v_4_6_10 200
 UP bnd v_4_6_11 100
 UP bnd v_4_6_12 100
 UP bnd v_4_6_13 100
 UP bnd v_1_7_9 100
 UP bnd v_1_7_10 200
 UP bnd v_1_7_11 100
 UP bnd v_1_7_12 100
 UP bnd v_1_7_13 100
 UP bnd v_2_7_9 100
 UP bnd v_2_7_10 200
 UP bnd v_2_7_11 100
 UP bnd v_2_7_12 100
 UP bnd v_2_7_13 100
 UP bnd v_3_7_9 50
 UP bnd v_3_7_10 50
 UP bnd v_3_7_11 50
 UP bnd v_3_7_12 50
 UP bnd v_3_7_13 50
 UP bnd v_4_7_9 100
 UP bnd v_4_7_10 200
 UP bnd v_4_7_11 100
 UP bnd v_4_7_12 100
 UP bnd v_4_7_13 100
 UP bnd v_1_8_9 100
 UP bnd v_1_8_10 200
 UP bnd v_1_8_11 100
 UP bnd v_1_8_12 100
 UP bnd v_1_8_13 100
 UP bnd v_2_8_9 100
 UP bnd v_2_8_10 200
 UP bnd v_2_8_11 100
 UP bnd v_2_8_12 100
 UP bnd v_2_8_13 100
 UP bnd v_3_8_9 50
 UP bnd v_3_8_10 50
 UP bnd v_3_8_11 50
 UP bnd v_3_8_12 50
 UP bnd v_3_8_13 50
 UP bnd v_4_8_9 100
 UP bnd v_4_8_10 200
 UP bnd v_4_8_11 100
 UP bnd v_4_8_12 100
 UP bnd v_4_8_13 100
QCMATRIX path_1_6_9
 f_6_9 q_1_6 -0.5
 q_1_6 f_6_9 -0.5
QCMATRIX path_1_6_10
 f_6_10 q_1_6 -0.5
 q_1_6 f_6_10 -0.5
QCMATRIX path_1_6_11
 f_6_11 q_1_6 -0.5
 q_1_6 f_6_11 -0.5
QCMATRIX path_1_6_12
 f_6_12 q_1_6 -0.5
 q_1_6 f_6_12 -0.5
QCMATRIX path_1_6_13
 f_6_13 q_1_6 -0.5
 q_1_6 f_6_13 -0.5
QCMATRIX path_2_6_9
 f_6_9 q_2_6 -0.5
 q_2_6 f_6_9 -0.5
QCMATRIX path_2_6_10
 f_6_10 q_2_6 -0.5
 q_2_6 f_6_10 -0.5
QCMATRIX path_2_6_11
 f_6_11 q_2_6 -0.5
 q_2_6 f_6_11 -0.5
QCMATRIX path_2_6_12
 f_6_12 q_2_6 -0.5
 q_2_6 f_6_12 -0.5
QCMATRIX path_2_6_13
 f_6_13 q_2_6 -0.5
 q_2_6 f_6_13 -0.5
QCMATRIX path_3_6_9
 f_6_9 q_3_6 -0.5
 q_3_6 f_6_9 -0.5
QCMATRIX path_3_6_10
 f_6_10 q_3_6 -0.5
 q_3_6 f_6_10 -0.5
QCMATRIX path_3_6_11
 f_6_11 q_3_6 -0.5
 q_3_6 f_6_11 -0.5
QCMATRIX path_3_6_12
 f_6_12 q_3_6 -0.5
 q_3_6 f_6_12 -0.5
QCMATRIX path_3_6_13
 f_6_13 q_3_6 -0.5
 q_3_6 f_6_13 -0.5
QCMATRIX path_4_6_9
 f_6_9 q_4_6 -0.5
 q_4_6 f_6_9 -0.5
QCMATRIX path_4_6_10
 f_6_10 q_4_6 -0.5
 q_4_6 f_6_10 -0.5
QCMATRIX path_4_6_11
 f_6_11 q_4_6 -0.5
 q_4_6 f_6_11 -0.5
QCMATRIX path_4_6_12
 f_6_12 q_4_6 -0.5
 q_4_6 f_6_12 -0.5
QCMATRIX path_4_6_13
 f_6_13 q_4_6 -0.5
 q_4_6 f_6_13 -0.5
QCMATRIX path_1_7_9
 f_7_9 q_1_7 -0.5
 q_1_7 f_7_9 -0.5
QCMATRIX path_1_7_10
 f_7_10 q_1_7 -0.5
 q_1_7 f_7_10 -0.5
QCMATRIX path_1_7_11
 f_7_11 q_1_7 -0.5
 q_1_7 f_7_11 -0.5
QCMATRIX path_1_7_12
 f_7_12 q_1_7 -0.5
 q_1_7 f_7_12 -0.5
QCMATRIX path_1_7_13
 f_7_13 q_1_7 -0.5
 q_1_7 f_7_13 -0.5
QCMATRIX path_2_7_9
 f_7_9 q_2_7 -0.5
 q_2_7 f_7_9 -0.5
QCMATRIX path_2_7_10
 f_7_10 q_2_7 -0.5
 q_2_7 f_7_10 -0.5
QCMATRIX path_2_7_11
 f_7_11 q_2_7 -0.5
 q_2_7 f_7_11 -0.5
QCMATRIX path_2_7_12
 f_7_12 q_2_7 -0.5
 q_2_7 f_7_12 -0.5
QCMATRIX path_2_7_13
 f_7_13 q_2_7 -0.5
 q_2_7 f_7_13 -0.5
QCMATRIX path_3_7_9
 f_7_9 q_3_7 -0.5
 q_3_7 f_7_9 -0.5
QCMATRIX path_3_7_10
 f_7_10 q_3_7 -0.5
 q_3_7 f_7_10 -0.5
QCMATRIX path_3_7_11
 f_7_11 q_3_7 -0.5
 q_3_7 f_7_11 -0.5
QCMATRIX path_3_7_12
 f_7_12 q_3_7 -0.5
 q_3_7 f_7_12 -0.5
QCMATRIX path_3_7_13
 f_7_13 q_3_7 -0.5
 q_3_7 f_7_13 -0.5
QCMATRIX path_4_7_9
 f_7_9 q_4_7 -0.5
 q_4_7 f_7_9 -0.5
QCMATRIX path_4_7_10
 f_7_10 q_4_7 -0.5
 q_4_7 f_7_10 -0.5
QCMATRIX path_4_7_11
 f_7_11 q_4_7 -0.5
 q_4_7 f_7_11 -0.5
QCMATRIX path_4_7_12
 f_7_12 q_4_7 -0.5
 q_4_7 f_7_12 -0.5
QCMATRIX path_4_7_13
 f_7_13 q_4_7 -0.5
 q_4_7 f_7_13 -0.5
QCMATRIX path_1_8_9
 f_8_9 q_1_8 -0.5
 q_1_8 f_8_9 -0.5
QCMATRIX path_1_8_10
 f_8_10 q_1_8 -0.5
 q_1_8 f_8_10 -0.5
QCMATRIX path_1_8_11
 f_8_11 q_1_8 -0.5
 q_1_8 f_8_11 -0.5
QCMATRIX path_1_8_12
 f_8_12 q_1_8 -0.5
 q_1_8 f_8_12 -0.5
QCMATRIX path_1_8_13
 f_8_13 q_1_8 -0.5
 q_1_8 f_8_13 -0.5
QCMATRIX path_2_8_9
 f_8_9 q_2_8 -0.5
 q_2_8 f_8_9 -0.5
QCMATRIX path_2_8_10
 f_8_10 q_2_8 -0.5
 q_2_8 f_8_10 -0.5
QCMATRIX path_2_8_11
 f_8_11 q_2_8 -0.5
 q_2_8 f_8_11 -0.5
QCMATRIX path_2_8_12
 f_8_12 q_2_8 -0.5
 q_2_8 f_8_12 -0.5
QCMATRIX path_2_8_13
 f_8_13 q_2_8 -0.5
 q_2_8 f_8_13 -0.5
QCMATRIX path_3_8_9
 f_8_9 q_3_8 -0.5
 q_3_8 f_8_9 -0.5
QCMATRIX path_3_8_10
 f_8_10 q_3_8 -0.5
 q_3_8 f_8_10 -0.5
QCMATRIX path_3_8_11
 f_8_11 q_3_8 -0.5
 q_3_8 f_8_11 -0.5
QCMATRIX path_3_8_12
 f_8_12 q_3_8 -0.5
 q_3_8 f_8_12 -0.5
QCMATRIX path_3_8_13
 f_8_13 q_3_8 -0.5
 q_3_8 f_8_13 -0.5
QCMATRIX path_4_8_9
 f_8_9 q_4_8 -0.5
 q_4_8 f_8_9 -0.5
QCMATRIX path_4_8_10
 f_8_10 q_4_8 -0.5
 q_4_8 f_8_10 -0.5
QCMATRIX path_4_8_11
 f_8_11 q_4_8 -0.5
 q_4_8 f_8_11 -0.5
QCMATRIX path_4_8_12
 f_8_12 q_4_8 -0.5
 q_4_8 f_8_12 -0.5
QCMATRIX path_4_8_13
 f_8_13 q_4_8 -0.5
 q_4_8 f_8_13 -0.5
ENDATA
