* SANKHYA pooling instance bental5, P-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/bental5.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Bental5.gms
* (sha256 2b4447361cd8d07852677e7491040779fa75da9192883d23a697dd2da89ebffc).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* P-formulation (Haverly 1978; Tawarmalani and Sahinidis 2002, ch. 9)
NAME bental5_p
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L src_5
 L dem_9
 L dem_10
 L dem_11
 L dem_12
 L dem_13
 E bal_6
 L cap_6
 E pq_6_1
 E pq_6_2
 E bal_7
 L cap_7
 E pq_7_1
 E pq_7_2
 E bal_8
 L cap_8
 E pq_8_1
 E pq_8_2
 L tq_9_1
 L tq_9_2
 L tq_10_1
 L tq_10_2
 L tq_11_1
 L tq_11_2
 L tq_12_1
 L tq_12_2
 L tq_13_1
 L tq_13_2
COLUMNS
 f_1_6 cost 6
 f_1_6 src_1 1
 f_1_6 bal_6 1
 f_1_6 cap_6 1
 f_1_6 pq_6_1 3
 f_1_6 pq_6_2 1
 f_1_7 cost 6
 f_1_7 src_1 1
 f_1_7 bal_7 1
 f_1_7 cap_7 1
 f_1_7 pq_7_1 3
 f_1_7 pq_7_2 1
 f_1_8 cost 6
 f_1_8 src_1 1
 f_1_8 bal_8 1
 f_1_8 cap_8 1
 f_1_8 pq_8_1 3
 f_1_8 pq_8_2 1
 f_2_6 cost 16
 f_2_6 src_2 1
 f_2_6 bal_6 1
 f_2_6 cap_6 1
 f_2_6 pq_6_1 1
 f_2_6 pq_6_2 3
 f_2_7 cost 16
 f_2_7 src_2 1
 f_2_7 bal_7 1
 f_2_7 cap_7 1
 f_2_7 pq_7_1 1
 f_2_7 pq_7_2 3
 f_2_8 cost 16
 f_2_8 src_2 1
 f_2_8 bal_8 1
 f_2_8 cap_8 1
 f_2_8 pq_8_1 1
 f_2_8 pq_8_2 3
 f_3_6 cost 15
 f_3_6 src_3 1
 f_3_6 bal_6 1
 f_3_6 cap_6 1
 f_3_6 pq_6_1 1
 f_3_6 pq_6_2 2.5
 f_3_7 cost 15
 f_3_7 src_3 1
 f_3_7 bal_7 1
 f_3_7 cap_7 1
 f_3_7 pq_7_1 1
 f_3_7 pq_7_2 2.5
 f_3_8 cost 15
 f_3_8 src_3 1
 f_3_8 bal_8 1
 f_3_8 cap_8 1
 f_3_8 pq_8_1 1
 f_3_8 pq_8_2 2.5
 f_4_6 cost 12
 f_4_6 src_4 1
 f_4_6 bal_6 1
 f_4_6 cap_6 1
 f_4_6 pq_6_1 1.5
 f_4_6 pq_6_2 2.5
 f_4_7 cost 12
 f_4_7 src_4 1
 f_4_7 bal_7 1
 f_4_7 cap_7 1
 f_4_7 pq_7_1 1.5
 f_4_7 pq_7_2 2.5
 f_4_8 cost 12
 f_4_8 src_4 1
 f_4_8 bal_8 1
 f_4_8 cap_8 1
 f_4_8 pq_8_1 1.5
 f_4_8 pq_8_2 2.5
 f_5_9 cost -8
 f_5_9 src_5 1
 f_5_9 dem_9 1
 f_5_9 tq_9_1 -0.5
 f_5_9 tq_9_2 0.5
 f_5_10 cost -5
 f_5_10 src_5 1
 f_5_10 dem_10 1
 f_5_10 tq_10_1 0.5
 f_5_11 cost -9
 f_5_11 src_5 1
 f_5_11 dem_11 1
 f_5_11 tq_11_2 -0.10000000000000009
 f_5_12 cost -6
 f_5_12 src_5 1
 f_5_12 dem_12 1
 f_5_12 tq_12_2 0.5
 f_5_13 cost -4
 f_5_13 src_5 1
 f_5_13 dem_13 1
 f_5_13 tq_13_2 0.5
 f_6_9 cost -18
 f_6_9 dem_9 1
 f_6_9 bal_6 -1
 f_6_9 tq_9_1 -2.5
 f_6_9 tq_9_2 -2
 f_6_10 cost -15
 f_6_10 dem_10 1
 f_6_10 bal_6 -1
 f_6_10 tq_10_1 -1.5
 f_6_10 tq_10_2 -2.5
 f_6_11 cost -19
 f_6_11 dem_11 1
 f_6_11 bal_6 -1
 f_6_11 tq_11_1 -2
 f_6_11 tq_11_2 -2.6
 f_6_12 cost -16
 f_6_12 dem_12 1
 f_6_12 bal_6 -1
 f_6_12 tq_12_1 -2
 f_6_12 tq_12_2 -2
 f_6_13 cost -14
 f_6_13 dem_13 1
 f_6_13 bal_6 -1
 f_6_13 tq_13_1 -2
 f_6_13 tq_13_2 -2
 f_7_9 cost -18
 f_7_9 dem_9 1
 f_7_9 bal_7 -1
 f_7_9 tq_9_1 -2.5
 f_7_9 tq_9_2 -2
 f_7_10 cost -15
 f_7_10 dem_10 1
 f_7_10 bal_7 -1
 f_7_10 tq_10_1 -1.5
 f_7_10 tq_10_2 -2.5
 f_7_11 cost -19
 f_7_11 dem_11 1
 f_7_11 bal_7 -1
 f_7_11 tq_11_1 -2
 f_7_11 tq_11_2 -2.6
 f_7_12 cost -16
 f_7_12 dem_12 1
 f_7_12 bal_7 -1
 f_7_12 tq_12_1 -2
 f_7_12 tq_12_2 -2
 f_7_13 cost -14
 f_7_13 dem_13 1
 f_7_13 bal_7 -1
 f_7_13 tq_13_1 -2
 f_7_13 tq_13_2 -2
 f_8_9 cost -18
 f_8_9 dem_9 1
 f_8_9 bal_8 -1
 f_8_9 tq_9_1 -2.5
 f_8_9 tq_9_2 -2
 f_8_10 cost -15
 f_8_10 dem_10 1
 f_8_10 bal_8 -1
 f_8_10 tq_10_1 -1.5
 f_8_10 tq_10_2 -2.5
 f_8_11 cost -19
 f_8_11 dem_11 1
 f_8_11 bal_8 -1
 f_8_11 tq_11_1 -2
 f_8_11 tq_11_2 -2.6
 f_8_12 cost -16
 f_8_12 dem_12 1
 f_8_12 bal_8 -1
 f_8_12 tq_12_1 -2
 f_8_12 tq_12_2 -2
 f_8_13 cost -14
 f_8_13 dem_13 1
 f_8_13 bal_8 -1
 f_8_13 tq_13_1 -2
 f_8_13 tq_13_2 -2
 p_6_1 cost 0
 p_6_2 cost 0
 p_7_1 cost 0
 p_7_2 cost 0
 p_8_1 cost 0
 p_8_2 cost 0
RHS
 rhs src_1 600
 rhs src_2 600
 rhs src_3 50
 rhs src_4 600
 rhs src_5 600
 rhs dem_9 100
 rhs dem_10 200
 rhs dem_11 100
 rhs dem_12 100
 rhs dem_13 100
 rhs cap_6 600
 rhs cap_7 600
 rhs cap_8 600
BOUNDS
 UP bnd f_1_6 600
 UP bnd f_1_7 600
 UP bnd f_1_8 600
 UP bnd f_2_6 600
 UP bnd f_2_7 600
 UP bnd f_2_8 600
 UP bnd f_3_6 50
 UP bnd f_3_7 50
 UP bnd f_3_8 50
 UP bnd f_4_6 600
 UP bnd f_4_7 600
 UP bnd f_4_8 600
 UP bnd f_5_9 100
 UP bnd f_5_10 200
 UP bnd f_5_11 100
 UP bnd f_5_12 100
 UP bnd f_5_13 100
 UP bnd f_6_9 100
 UP bnd f_6_10 200
 UP bnd f_6_11 100
 UP bnd f_6_12 100
 UP bnd f_6_13 100
 UP bnd f_7_9 100
 UP bnd f_7_10 200
 UP bnd f_7_11 100
 UP bnd f_7_12 100
 UP bnd f_7_13 100
 UP bnd f_8_9 100
 UP bnd f_8_10 200
 UP bnd f_8_11 100
 UP bnd f_8_12 100
 UP bnd f_8_13 100
 LO bnd p_6_1 1
 UP bnd p_6_1 3
 LO bnd p_6_2 1
 UP bnd p_6_2 3
 LO bnd p_7_1 1
 UP bnd p_7_1 3
 LO bnd p_7_2 1
 UP bnd p_7_2 3
 LO bnd p_8_1 1
 UP bnd p_8_1 3
 LO bnd p_8_2 1
 UP bnd p_8_2 3
QCMATRIX pq_6_1
 f_6_9 p_6_1 -0.5
 p_6_1 f_6_9 -0.5
 f_6_10 p_6_1 -0.5
 p_6_1 f_6_10 -0.5
 f_6_11 p_6_1 -0.5
 p_6_1 f_6_11 -0.5
 f_6_12 p_6_1 -0.5
 p_6_1 f_6_12 -0.5
 f_6_13 p_6_1 -0.5
 p_6_1 f_6_13 -0.5
QCMATRIX pq_6_2
 f_6_9 p_6_2 -0.5
 p_6_2 f_6_9 -0.5
 f_6_10 p_6_2 -0.5
 p_6_2 f_6_10 -0.5
 f_6_11 p_6_2 -0.5
 p_6_2 f_6_11 -0.5
 f_6_12 p_6_2 -0.5
 p_6_2 f_6_12 -0.5
 f_6_13 p_6_2 -0.5
 p_6_2 f_6_13 -0.5
QCMATRIX pq_7_1
 f_7_9 p_7_1 -0.5
 p_7_1 f_7_9 -0.5
 f_7_10 p_7_1 -0.5
 p_7_1 f_7_10 -0.5
 f_7_11 p_7_1 -0.5
 p_7_1 f_7_11 -0.5
 f_7_12 p_7_1 -0.5
 p_7_1 f_7_12 -0.5
 f_7_13 p_7_1 -0.5
 p_7_1 f_7_13 -0.5
QCMATRIX pq_7_2
 f_7_9 p_7_2 -0.5
 p_7_2 f_7_9 -0.5
 f_7_10 p_7_2 -0.5
 p_7_2 f_7_10 -0.5
 f_7_11 p_7_2 -0.5
 p_7_2 f_7_11 -0.5
 f_7_12 p_7_2 -0.5
 p_7_2 f_7_12 -0.5
 f_7_13 p_7_2 -0.5
 p_7_2 f_7_13 -0.5
QCMATRIX pq_8_1
 f_8_9 p_8_1 -0.5
 p_8_1 f_8_9 -0.5
 f_8_10 p_8_1 -0.5
 p_8_1 f_8_10 -0.5
 f_8_11 p_8_1 -0.5
 p_8_1 f_8_11 -0.5
 f_8_12 p_8_1 -0.5
 p_8_1 f_8_12 -0.5
 f_8_13 p_8_1 -0.5
 p_8_1 f_8_13 -0.5
QCMATRIX pq_8_2
 f_8_9 p_8_2 -0.5
 p_8_2 f_8_9 -0.5
 f_8_10 p_8_2 -0.5
 p_8_2 f_8_10 -0.5
 f_8_11 p_8_2 -0.5
 p_8_2 f_8_11 -0.5
 f_8_12 p_8_2 -0.5
 p_8_2 f_8_12 -0.5
 f_8_13 p_8_2 -0.5
 p_8_2 f_8_13 -0.5
QCMATRIX tq_9_1
 f_6_9 p_6_1 0.5
 p_6_1 f_6_9 0.5
 f_7_9 p_7_1 0.5
 p_7_1 f_7_9 0.5
 f_8_9 p_8_1 0.5
 p_8_1 f_8_9 0.5
QCMATRIX tq_9_2
 f_6_9 p_6_2 0.5
 p_6_2 f_6_9 0.5
 f_7_9 p_7_2 0.5
 p_7_2 f_7_9 0.5
 f_8_9 p_8_2 0.5
 p_8_2 f_8_9 0.5
QCMATRIX tq_10_1
 f_6_10 p_6_1 0.5
 p_6_1 f_6_10 0.5
 f_7_10 p_7_1 0.5
 p_7_1 f_7_10 0.5
 f_8_10 p_8_1 0.5
 p_8_1 f_8_10 0.5
QCMATRIX tq_10_2
 f_6_10 p_6_2 0.5
 p_6_2 f_6_10 0.5
 f_7_10 p_7_2 0.5
 p_7_2 f_7_10 0.5
 f_8_10 p_8_2 0.5
 p_8_2 f_8_10 0.5
QCMATRIX tq_11_1
 f_6_11 p_6_1 0.5
 p_6_1 f_6_11 0.5
 f_7_11 p_7_1 0.5
 p_7_1 f_7_11 0.5
 f_8_11 p_8_1 0.5
 p_8_1 f_8_11 0.5
QCMATRIX tq_11_2
 f_6_11 p_6_2 0.5
 p_6_2 f_6_11 0.5
 f_7_11 p_7_2 0.5
 p_7_2 f_7_11 0.5
 f_8_11 p_8_2 0.5
 p_8_2 f_8_11 0.5
QCMATRIX tq_12_1
 f_6_12 p_6_1 0.5
 p_6_1 f_6_12 0.5
 f_7_12 p_7_1 0.5
 p_7_1 f_7_12 0.5
 f_8_12 p_8_1 0.5
 p_8_1 f_8_12 0.5
QCMATRIX tq_12_2
 f_6_12 p_6_2 0.5
 p_6_2 f_6_12 0.5
 f_7_12 p_7_2 0.5
 p_7_2 f_7_12 0.5
 f_8_12 p_8_2 0.5
 p_8_2 f_8_12 0.5
QCMATRIX tq_13_1
 f_6_13 p_6_1 0.5
 p_6_1 f_6_13 0.5
 f_7_13 p_7_1 0.5
 p_7_1 f_7_13 0.5
 f_8_13 p_8_1 0.5
 p_8_1 f_8_13 0.5
QCMATRIX tq_13_2
 f_6_13 p_6_2 0.5
 p_6_2 f_6_13 0.5
 f_7_13 p_7_2 0.5
 p_7_2 f_7_13 0.5
 f_8_13 p_8_2 0.5
 p_8_2 f_8_13 0.5
ENDATA
