* SANKHYA pooling instance bental4, Q-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/bental4.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Bental4.gms
* (sha256 6cee84a21896e6104766f8a46641cd030f730995580dca674bbcaa9c2f042d51).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* Q-formulation (Ben-Tal, Eiger and Gershovitz 1994), path flows as columns
NAME bental4_q
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L dem_6
 L dem_7
 E sumq_5
 L cap_5
 L tq_6_1
 L tq_7_1
 E path_1_5_6
 E path_1_5_7
 E path_2_5_6
 E path_2_5_7
 E path_3_5_6
 E path_3_5_7
COLUMNS
 q_1_5 sumq_5 1
 q_2_5 sumq_5 1
 q_3_5 sumq_5 1
 f_4_6 cost 1
 f_4_6 src_4 1
 f_4_6 dem_6 1
 f_4_6 tq_6_1 -0.5
 f_4_7 cost -5
 f_4_7 src_4 1
 f_4_7 dem_7 1
 f_4_7 tq_7_1 0.5
 f_5_6 cost -9
 f_5_6 dem_6 1
 f_5_6 cap_5 1
 f_5_6 tq_6_1 -2.5
 f_5_7 cost -15
 f_5_7 dem_7 1
 f_5_7 cap_5 1
 f_5_7 tq_7_1 -1.5
 v_1_5_6 cost 6
 v_1_5_6 src_1 1
 v_1_5_6 tq_6_1 3
 v_1_5_6 path_1_5_6 1
 v_1_5_7 cost 6
 v_1_5_7 src_1 1
 v_1_5_7 tq_7_1 3
 v_1_5_7 path_1_5_7 1
 v_2_5_6 cost 15
 v_2_5_6 src_2 1
 v_2_5_6 tq_6_1 1
 v_2_5_6 path_2_5_6 1
 v_2_5_7 cost 15
 v_2_5_7 src_2 1
 v_2_5_7 tq_7_1 1
 v_2_5_7 path_2_5_7 1
 v_3_5_6 cost 16
 v_3_5_6 src_3 1
 v_3_5_6 tq_6_1 1
 v_3_5_6 path_3_5_6 1
 v_3_5_7 cost 16
 v_3_5_7 src_3 1
 v_3_5_7 tq_7_1 1
 v_3_5_7 path_3_5_7 1
RHS
 rhs src_1 300
 rhs src_2 50
 rhs src_3 300
 rhs src_4 300
 rhs dem_6 100
 rhs dem_7 200
 rhs sumq_5 1
 rhs cap_5 300
BOUNDS
 UP bnd q_1_5 1
 UP bnd q_2_5 1
 UP bnd q_3_5 1
 UP bnd f_4_6 100
 UP bnd f_4_7 200
 UP bnd f_5_6 100
 UP bnd f_5_7 200
 UP bnd v_1_5_6 100
 UP bnd v_1_5_7 200
 UP bnd v_2_5_6 50
 UP bnd v_2_5_7 50
 UP bnd v_3_5_6 100
 UP bnd v_3_5_7 200
QCMATRIX path_1_5_6
 f_5_6 q_1_5 -0.5
 q_1_5 f_5_6 -0.5
QCMATRIX path_1_5_7
 f_5_7 q_1_5 -0.5
 q_1_5 f_5_7 -0.5
QCMATRIX path_2_5_6
 f_5_6 q_2_5 -0.5
 q_2_5 f_5_6 -0.5
QCMATRIX path_2_5_7
 f_5_7 q_2_5 -0.5
 q_2_5 f_5_7 -0.5
QCMATRIX path_3_5_6
 f_5_6 q_3_5 -0.5
 q_3_5 f_5_6 -0.5
QCMATRIX path_3_5_7
 f_5_7 q_3_5 -0.5
 q_3_5 f_5_7 -0.5
ENDATA
