* SANKHYA pooling instance bental4, P-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/bental4.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Bental4.gms
* (sha256 6cee84a21896e6104766f8a46641cd030f730995580dca674bbcaa9c2f042d51).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* P-formulation (Haverly 1978; Tawarmalani and Sahinidis 2002, ch. 9)
NAME bental4_p
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L dem_6
 L dem_7
 E bal_5
 L cap_5
 E pq_5_1
 L tq_6_1
 L tq_7_1
COLUMNS
 f_1_5 cost 6
 f_1_5 src_1 1
 f_1_5 bal_5 1
 f_1_5 cap_5 1
 f_1_5 pq_5_1 3
 f_2_5 cost 15
 f_2_5 src_2 1
 f_2_5 bal_5 1
 f_2_5 cap_5 1
 f_2_5 pq_5_1 1
 f_3_5 cost 16
 f_3_5 src_3 1
 f_3_5 bal_5 1
 f_3_5 cap_5 1
 f_3_5 pq_5_1 1
 f_4_6 cost 1
 f_4_6 src_4 1
 f_4_6 dem_6 1
 f_4_6 tq_6_1 -0.5
 f_4_7 cost -5
 f_4_7 src_4 1
 f_4_7 dem_7 1
 f_4_7 tq_7_1 0.5
 f_5_6 cost -9
 f_5_6 dem_6 1
 f_5_6 bal_5 -1
 f_5_6 tq_6_1 -2.5
 f_5_7 cost -15
 f_5_7 dem_7 1
 f_5_7 bal_5 -1
 f_5_7 tq_7_1 -1.5
 p_5_1 cost 0
RHS
 rhs src_1 300
 rhs src_2 50
 rhs src_3 300
 rhs src_4 300
 rhs dem_6 100
 rhs dem_7 200
 rhs cap_5 300
BOUNDS
 UP bnd f_1_5 300
 UP bnd f_2_5 50
 UP bnd f_3_5 300
 UP bnd f_4_6 100
 UP bnd f_4_7 200
 UP bnd f_5_6 100
 UP bnd f_5_7 200
 LO bnd p_5_1 1
 UP bnd p_5_1 3
QCMATRIX pq_5_1
 f_5_6 p_5_1 -0.5
 p_5_1 f_5_6 -0.5
 f_5_7 p_5_1 -0.5
 p_5_1 f_5_7 -0.5
QCMATRIX tq_6_1
 f_5_6 p_5_1 0.5
 p_5_1 f_5_6 0.5
QCMATRIX tq_7_1
 f_5_7 p_5_1 0.5
 p_5_1 f_5_7 0.5
ENDATA
