* SANKHYA pooling instance foulds2, P-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/foulds2.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Foulds2.gms
* (sha256 a96902e5d26544872000666ee639fd5e2f06258a7c1503418aee6cbbe98b3ea5).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* P-formulation (Haverly 1978; Tawarmalani and Sahinidis 2002, ch. 9)
NAME foulds2_p
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L src_5
 L src_6
 L dem_9
 L dem_10
 L dem_11
 L dem_12
 E bal_7
 L cap_7
 E pq_7_1
 E bal_8
 L cap_8
 E pq_8_1
 L tq_9_1
 L tq_10_1
 L tq_11_1
 L tq_12_1
COLUMNS
 f_1_7 cost 6
 f_1_7 src_1 1
 f_1_7 bal_7 1
 f_1_7 cap_7 1
 f_1_7 pq_7_1 3
 f_2_7 cost 16
 f_2_7 src_2 1
 f_2_7 bal_7 1
 f_2_7 cap_7 1
 f_2_7 pq_7_1 1
 f_3_9 cost 1
 f_3_9 src_3 1
 f_3_9 dem_9 1
 f_3_9 tq_9_1 -0.5
 f_3_10 cost -5
 f_3_10 src_3 1
 f_3_10 dem_10 1
 f_3_10 tq_10_1 0.5
 f_3_11 cost 4
 f_3_11 src_3 1
 f_3_11 dem_11 1
 f_3_11 tq_11_1 -1
 f_3_12 cost -2
 f_3_12 src_3 1
 f_3_12 dem_12 1
 f_4_8 cost 3
 f_4_8 src_4 1
 f_4_8 bal_8 1
 f_4_8 cap_8 1
 f_4_8 pq_8_1 3.5
 f_5_8 cost 13
 f_5_8 src_5 1
 f_5_8 bal_8 1
 f_5_8 cap_8 1
 f_5_8 pq_8_1 1.5
 f_6_9 cost -2
 f_6_9 src_6 1
 f_6_9 dem_9 1
 f_6_10 cost -8
 f_6_10 src_6 1
 f_6_10 dem_10 1
 f_6_10 tq_10_1 1
 f_6_11 cost 1
 f_6_11 src_6 1
 f_6_11 dem_11 1
 f_6_11 tq_11_1 -0.5
 f_6_12 cost -5
 f_6_12 src_6 1
 f_6_12 dem_12 1
 f_6_12 tq_12_1 0.5
 f_7_9 cost -9
 f_7_9 dem_9 1
 f_7_9 bal_7 -1
 f_7_9 tq_9_1 -2.5
 f_7_10 cost -15
 f_7_10 dem_10 1
 f_7_10 bal_7 -1
 f_7_10 tq_10_1 -1.5
 f_7_11 cost -6
 f_7_11 dem_11 1
 f_7_11 bal_7 -1
 f_7_11 tq_11_1 -3
 f_7_12 cost -12
 f_7_12 dem_12 1
 f_7_12 bal_7 -1
 f_7_12 tq_12_1 -2
 f_8_9 cost -9
 f_8_9 dem_9 1
 f_8_9 bal_8 -1
 f_8_9 tq_9_1 -2.5
 f_8_10 cost -15
 f_8_10 dem_10 1
 f_8_10 bal_8 -1
 f_8_10 tq_10_1 -1.5
 f_8_11 cost -6
 f_8_11 dem_11 1
 f_8_11 bal_8 -1
 f_8_11 tq_11_1 -3
 f_8_12 cost -12
 f_8_12 dem_12 1
 f_8_12 bal_8 -1
 f_8_12 tq_12_1 -2
 p_7_1 cost 0
 p_8_1 cost 0
RHS
 rhs src_1 600
 rhs src_2 600
 rhs src_3 600
 rhs src_4 600
 rhs src_5 600
 rhs src_6 600
 rhs dem_9 100
 rhs dem_10 200
 rhs dem_11 100
 rhs dem_12 200
 rhs cap_7 600
 rhs cap_8 600
BOUNDS
 UP bnd f_1_7 600
 UP bnd f_2_7 600
 UP bnd f_3_9 100
 UP bnd f_3_10 200
 UP bnd f_3_11 100
 UP bnd f_3_12 200
 UP bnd f_4_8 600
 UP bnd f_5_8 600
 UP bnd f_6_9 100
 UP bnd f_6_10 200
 UP bnd f_6_11 100
 UP bnd f_6_12 200
 UP bnd f_7_9 100
 UP bnd f_7_10 200
 UP bnd f_7_11 100
 UP bnd f_7_12 200
 UP bnd f_8_9 100
 UP bnd f_8_10 200
 UP bnd f_8_11 100
 UP bnd f_8_12 200
 LO bnd p_7_1 1
 UP bnd p_7_1 3
 LO bnd p_8_1 1.5
 UP bnd p_8_1 3.5
QCMATRIX pq_7_1
 f_7_9 p_7_1 -0.5
 p_7_1 f_7_9 -0.5
 f_7_10 p_7_1 -0.5
 p_7_1 f_7_10 -0.5
 f_7_11 p_7_1 -0.5
 p_7_1 f_7_11 -0.5
 f_7_12 p_7_1 -0.5
 p_7_1 f_7_12 -0.5
QCMATRIX pq_8_1
 f_8_9 p_8_1 -0.5
 p_8_1 f_8_9 -0.5
 f_8_10 p_8_1 -0.5
 p_8_1 f_8_10 -0.5
 f_8_11 p_8_1 -0.5
 p_8_1 f_8_11 -0.5
 f_8_12 p_8_1 -0.5
 p_8_1 f_8_12 -0.5
QCMATRIX tq_9_1
 f_7_9 p_7_1 0.5
 p_7_1 f_7_9 0.5
 f_8_9 p_8_1 0.5
 p_8_1 f_8_9 0.5
QCMATRIX tq_10_1
 f_7_10 p_7_1 0.5
 p_7_1 f_7_10 0.5
 f_8_10 p_8_1 0.5
 p_8_1 f_8_10 0.5
QCMATRIX tq_11_1
 f_7_11 p_7_1 0.5
 p_7_1 f_7_11 0.5
 f_8_11 p_8_1 0.5
 p_8_1 f_8_11 0.5
QCMATRIX tq_12_1
 f_7_12 p_7_1 0.5
 p_7_1 f_7_12 0.5
 f_8_12 p_8_1 0.5
 p_8_1 f_8_12 0.5
ENDATA
