* SANKHYA pooling instance foulds2, PQ-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/foulds2.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Foulds2.gms
* (sha256 a96902e5d26544872000666ee639fd5e2f06258a7c1503418aee6cbbe98b3ea5).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* PQ-formulation (Quesada and Grossmann 1995; Tawarmalani and Sahinidis 2002)
NAME foulds2_pq
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L src_4
 L src_5
 L src_6
 L dem_9
 L dem_10
 L dem_11
 L dem_12
 E sumq_7
 L cap_7
 E sumq_8
 L cap_8
 L tq_9_1
 L tq_10_1
 L tq_11_1
 L tq_12_1
 E path_1_7_9
 E path_1_7_10
 E path_1_7_11
 E path_1_7_12
 E path_2_7_9
 E path_2_7_10
 E path_2_7_11
 E path_2_7_12
 E path_4_8_9
 E path_4_8_10
 E path_4_8_11
 E path_4_8_12
 E path_5_8_9
 E path_5_8_10
 E path_5_8_11
 E path_5_8_12
 E rlt_7_9
 E rlt_7_10
 E rlt_7_11
 E rlt_7_12
 L rltc_1_7
 L rltc_2_7
 E rlt_8_9
 E rlt_8_10
 E rlt_8_11
 E rlt_8_12
 L rltc_4_8
 L rltc_5_8
COLUMNS
 q_1_7 sumq_7 1
 q_1_7 rltc_1_7 -600
 q_2_7 sumq_7 1
 q_2_7 rltc_2_7 -600
 q_4_8 sumq_8 1
 q_4_8 rltc_4_8 -600
 q_5_8 sumq_8 1
 q_5_8 rltc_5_8 -600
 f_3_9 cost 1
 f_3_9 src_3 1
 f_3_9 dem_9 1
 f_3_9 tq_9_1 -0.5
 f_3_10 cost -5
 f_3_10 src_3 1
 f_3_10 dem_10 1
 f_3_10 tq_10_1 0.5
 f_3_11 cost 4
 f_3_11 src_3 1
 f_3_11 dem_11 1
 f_3_11 tq_11_1 -1
 f_3_12 cost -2
 f_3_12 src_3 1
 f_3_12 dem_12 1
 f_6_9 cost -2
 f_6_9 src_6 1
 f_6_9 dem_9 1
 f_6_10 cost -8
 f_6_10 src_6 1
 f_6_10 dem_10 1
 f_6_10 tq_10_1 1
 f_6_11 cost 1
 f_6_11 src_6 1
 f_6_11 dem_11 1
 f_6_11 tq_11_1 -0.5
 f_6_12 cost -5
 f_6_12 src_6 1
 f_6_12 dem_12 1
 f_6_12 tq_12_1 0.5
 f_7_9 cost -9
 f_7_9 dem_9 1
 f_7_9 cap_7 1
 f_7_9 tq_9_1 -2.5
 f_7_9 rlt_7_9 -1
 f_7_10 cost -15
 f_7_10 dem_10 1
 f_7_10 cap_7 1
 f_7_10 tq_10_1 -1.5
 f_7_10 rlt_7_10 -1
 f_7_11 cost -6
 f_7_11 dem_11 1
 f_7_11 cap_7 1
 f_7_11 tq_11_1 -3
 f_7_11 rlt_7_11 -1
 f_7_12 cost -12
 f_7_12 dem_12 1
 f_7_12 cap_7 1
 f_7_12 tq_12_1 -2
 f_7_12 rlt_7_12 -1
 f_8_9 cost -9
 f_8_9 dem_9 1
 f_8_9 cap_8 1
 f_8_9 tq_9_1 -2.5
 f_8_9 rlt_8_9 -1
 f_8_10 cost -15
 f_8_10 dem_10 1
 f_8_10 cap_8 1
 f_8_10 tq_10_1 -1.5
 f_8_10 rlt_8_10 -1
 f_8_11 cost -6
 f_8_11 dem_11 1
 f_8_11 cap_8 1
 f_8_11 tq_11_1 -3
 f_8_11 rlt_8_11 -1
 f_8_12 cost -12
 f_8_12 dem_12 1
 f_8_12 cap_8 1
 f_8_12 tq_12_1 -2
 f_8_12 rlt_8_12 -1
 v_1_7_9 cost 6
 v_1_7_9 src_1 1
 v_1_7_9 tq_9_1 3
 v_1_7_9 path_1_7_9 1
 v_1_7_9 rlt_7_9 1
 v_1_7_9 rltc_1_7 1
 v_1_7_10 cost 6
 v_1_7_10 src_1 1
 v_1_7_10 tq_10_1 3
 v_1_7_10 path_1_7_10 1
 v_1_7_10 rlt_7_10 1
 v_1_7_10 rltc_1_7 1
 v_1_7_11 cost 6
 v_1_7_11 src_1 1
 v_1_7_11 tq_11_1 3
 v_1_7_11 path_1_7_11 1
 v_1_7_11 rlt_7_11 1
 v_1_7_11 rltc_1_7 1
 v_1_7_12 cost 6
 v_1_7_12 src_1 1
 v_1_7_12 tq_12_1 3
 v_1_7_12 path_1_7_12 1
 v_1_7_12 rlt_7_12 1
 v_1_7_12 rltc_1_7 1
 v_2_7_9 cost 16
 v_2_7_9 src_2 1
 v_2_7_9 tq_9_1 1
 v_2_7_9 path_2_7_9 1
 v_2_7_9 rlt_7_9 1
 v_2_7_9 rltc_2_7 1
 v_2_7_10 cost 16
 v_2_7_10 src_2 1
 v_2_7_10 tq_10_1 1
 v_2_7_10 path_2_7_10 1
 v_2_7_10 rlt_7_10 1
 v_2_7_10 rltc_2_7 1
 v_2_7_11 cost 16
 v_2_7_11 src_2 1
 v_2_7_11 tq_11_1 1
 v_2_7_11 path_2_7_11 1
 v_2_7_11 rlt_7_11 1
 v_2_7_11 rltc_2_7 1
 v_2_7_12 cost 16
 v_2_7_12 src_2 1
 v_2_7_12 tq_12_1 1
 v_2_7_12 path_2_7_12 1
 v_2_7_12 rlt_7_12 1
 v_2_7_12 rltc_2_7 1
 v_4_8_9 cost 3
 v_4_8_9 src_4 1
 v_4_8_9 tq_9_1 3.5
 v_4_8_9 path_4_8_9 1
 v_4_8_9 rlt_8_9 1
 v_4_8_9 rltc_4_8 1
 v_4_8_10 cost 3
 v_4_8_10 src_4 1
 v_4_8_10 tq_10_1 3.5
 v_4_8_10 path_4_8_10 1
 v_4_8_10 rlt_8_10 1
 v_4_8_10 rltc_4_8 1
 v_4_8_11 cost 3
 v_4_8_11 src_4 1
 v_4_8_11 tq_11_1 3.5
 v_4_8_11 path_4_8_11 1
 v_4_8_11 rlt_8_11 1
 v_4_8_11 rltc_4_8 1
 v_4_8_12 cost 3
 v_4_8_12 src_4 1
 v_4_8_12 tq_12_1 3.5
 v_4_8_12 path_4_8_12 1
 v_4_8_12 rlt_8_12 1
 v_4_8_12 rltc_4_8 1
 v_5_8_9 cost 13
 v_5_8_9 src_5 1
 v_5_8_9 tq_9_1 1.5
 v_5_8_9 path_5_8_9 1
 v_5_8_9 rlt_8_9 1
 v_5_8_9 rltc_5_8 1
 v_5_8_10 cost 13
 v_5_8_10 src_5 1
 v_5_8_10 tq_10_1 1.5
 v_5_8_10 path_5_8_10 1
 v_5_8_10 rlt_8_10 1
 v_5_8_10 rltc_5_8 1
 v_5_8_11 cost 13
 v_5_8_11 src_5 1
 v_5_8_11 tq_11_1 1.5
 v_5_8_11 path_5_8_11 1
 v_5_8_11 rlt_8_11 1
 v_5_8_11 rltc_5_8 1
 v_5_8_12 cost 13
 v_5_8_12 src_5 1
 v_5_8_12 tq_12_1 1.5
 v_5_8_12 path_5_8_12 1
 v_5_8_12 rlt_8_12 1
 v_5_8_12 rltc_5_8 1
RHS
 rhs src_1 600
 rhs src_2 600
 rhs src_3 600
 rhs src_4 600
 rhs src_5 600
 rhs src_6 600
 rhs dem_9 100
 rhs dem_10 200
 rhs dem_11 100
 rhs dem_12 200
 rhs sumq_7 1
 rhs cap_7 600
 rhs sumq_8 1
 rhs cap_8 600
BOUNDS
 UP bnd q_1_7 1
 UP bnd q_2_7 1
 UP bnd q_4_8 1
 UP bnd q_5_8 1
 UP bnd f_3_9 100
 UP bnd f_3_10 200
 UP bnd f_3_11 100
 UP bnd f_3_12 200
 UP bnd f_6_9 100
 UP bnd f_6_10 200
 UP bnd f_6_11 100
 UP bnd f_6_12 200
 UP bnd f_7_9 100
 UP bnd f_7_10 200
 UP bnd f_7_11 100
 UP bnd f_7_12 200
 UP bnd f_8_9 100
 UP bnd f_8_10 200
 UP bnd f_8_11 100
 UP bnd f_8_12 200
 UP bnd v_1_7_9 100
 UP bnd v_1_7_10 200
 UP bnd v_1_7_11 100
 UP bnd v_1_7_12 200
 UP bnd v_2_7_9 100
 UP bnd v_2_7_10 200
 UP bnd v_2_7_11 100
 UP bnd v_2_7_12 200
 UP bnd v_4_8_9 100
 UP bnd v_4_8_10 200
 UP bnd v_4_8_11 100
 UP bnd v_4_8_12 200
 UP bnd v_5_8_9 100
 UP bnd v_5_8_10 200
 UP bnd v_5_8_11 100
 UP bnd v_5_8_12 200
QCMATRIX path_1_7_9
 f_7_9 q_1_7 -0.5
 q_1_7 f_7_9 -0.5
QCMATRIX path_1_7_10
 f_7_10 q_1_7 -0.5
 q_1_7 f_7_10 -0.5
QCMATRIX path_1_7_11
 f_7_11 q_1_7 -0.5
 q_1_7 f_7_11 -0.5
QCMATRIX path_1_7_12
 f_7_12 q_1_7 -0.5
 q_1_7 f_7_12 -0.5
QCMATRIX path_2_7_9
 f_7_9 q_2_7 -0.5
 q_2_7 f_7_9 -0.5
QCMATRIX path_2_7_10
 f_7_10 q_2_7 -0.5
 q_2_7 f_7_10 -0.5
QCMATRIX path_2_7_11
 f_7_11 q_2_7 -0.5
 q_2_7 f_7_11 -0.5
QCMATRIX path_2_7_12
 f_7_12 q_2_7 -0.5
 q_2_7 f_7_12 -0.5
QCMATRIX path_4_8_9
 f_8_9 q_4_8 -0.5
 q_4_8 f_8_9 -0.5
QCMATRIX path_4_8_10
 f_8_10 q_4_8 -0.5
 q_4_8 f_8_10 -0.5
QCMATRIX path_4_8_11
 f_8_11 q_4_8 -0.5
 q_4_8 f_8_11 -0.5
QCMATRIX path_4_8_12
 f_8_12 q_4_8 -0.5
 q_4_8 f_8_12 -0.5
QCMATRIX path_5_8_9
 f_8_9 q_5_8 -0.5
 q_5_8 f_8_9 -0.5
QCMATRIX path_5_8_10
 f_8_10 q_5_8 -0.5
 q_5_8 f_8_10 -0.5
QCMATRIX path_5_8_11
 f_8_11 q_5_8 -0.5
 q_5_8 f_8_11 -0.5
QCMATRIX path_5_8_12
 f_8_12 q_5_8 -0.5
 q_5_8 f_8_12 -0.5
ENDATA
