* SANKHYA pooling instance haverly2, P-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/haverly2.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Haverly2.gms
* (sha256 c04007d50ba05ee48dc04b71880048a54c518bccee3d0b49b5e89193a43e35b1).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* P-formulation (Haverly 1978; Tawarmalani and Sahinidis 2002, ch. 9)
NAME haverly2_p
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L dem_5
 L dem_6
 E bal_4
 L cap_4
 E pq_4_1
 L tq_5_1
 L tq_6_1
COLUMNS
 f_1_4 cost 6
 f_1_4 src_1 1
 f_1_4 bal_4 1
 f_1_4 cap_4 1
 f_1_4 pq_4_1 3
 f_2_4 cost 16
 f_2_4 src_2 1
 f_2_4 bal_4 1
 f_2_4 cap_4 1
 f_2_4 pq_4_1 1
 f_3_5 cost 1
 f_3_5 src_3 1
 f_3_5 dem_5 1
 f_3_5 tq_5_1 -0.5
 f_3_6 cost -5
 f_3_6 src_3 1
 f_3_6 dem_6 1
 f_3_6 tq_6_1 0.5
 f_4_5 cost -9
 f_4_5 dem_5 1
 f_4_5 bal_4 -1
 f_4_5 tq_5_1 -2.5
 f_4_6 cost -15
 f_4_6 dem_6 1
 f_4_6 bal_4 -1
 f_4_6 tq_6_1 -1.5
 p_4_1 cost 0
RHS
 rhs src_1 800
 rhs src_2 800
 rhs src_3 800
 rhs dem_5 600
 rhs dem_6 200
 rhs cap_4 800
BOUNDS
 UP bnd f_1_4 800
 UP bnd f_2_4 800
 UP bnd f_3_5 600
 UP bnd f_3_6 200
 UP bnd f_4_5 600
 UP bnd f_4_6 200
 LO bnd p_4_1 1
 UP bnd p_4_1 3
QCMATRIX pq_4_1
 f_4_5 p_4_1 -0.5
 p_4_1 f_4_5 -0.5
 f_4_6 p_4_1 -0.5
 p_4_1 f_4_6 -0.5
QCMATRIX tq_5_1
 f_4_5 p_4_1 0.5
 p_4_1 f_4_5 0.5
QCMATRIX tq_6_1
 f_4_6 p_4_1 0.5
 p_4_1 f_4_6 0.5
ENDATA
