* SANKHYA pooling instance haverly3, P-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/haverly3.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Haverly3.gms
* (sha256 95ff0b8b85d9961e46f5e5a4a89d99bd45b50b7d37244afecb547991e2b904c1).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* P-formulation (Haverly 1978; Tawarmalani and Sahinidis 2002, ch. 9)
NAME haverly3_p
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L dem_5
 L dem_6
 E bal_4
 L cap_4
 E pq_4_1
 L tq_5_1
 L tq_6_1
COLUMNS
 f_1_4 cost 6
 f_1_4 src_1 1
 f_1_4 bal_4 1
 f_1_4 cap_4 1
 f_1_4 pq_4_1 3
 f_2_4 cost 13
 f_2_4 src_2 1
 f_2_4 bal_4 1
 f_2_4 cap_4 1
 f_2_4 pq_4_1 1
 f_3_5 cost 1
 f_3_5 src_3 1
 f_3_5 dem_5 1
 f_3_5 tq_5_1 -0.5
 f_3_6 cost -5
 f_3_6 src_3 1
 f_3_6 dem_6 1
 f_3_6 tq_6_1 0.5
 f_4_5 cost -9
 f_4_5 dem_5 1
 f_4_5 bal_4 -1
 f_4_5 tq_5_1 -2.5
 f_4_6 cost -15
 f_4_6 dem_6 1
 f_4_6 bal_4 -1
 f_4_6 tq_6_1 -1.5
 p_4_1 cost 0
RHS
 rhs src_1 300
 rhs src_2 300
 rhs src_3 300
 rhs dem_5 100
 rhs dem_6 200
 rhs cap_4 300
BOUNDS
 UP bnd f_1_4 300
 UP bnd f_2_4 300
 UP bnd f_3_5 100
 UP bnd f_3_6 200
 UP bnd f_4_5 100
 UP bnd f_4_6 200
 LO bnd p_4_1 1
 UP bnd p_4_1 3
QCMATRIX pq_4_1
 f_4_5 p_4_1 -0.5
 p_4_1 f_4_5 -0.5
 f_4_6 p_4_1 -0.5
 p_4_1 f_4_6 -0.5
QCMATRIX tq_5_1
 f_4_5 p_4_1 0.5
 p_4_1 f_4_5 0.5
QCMATRIX tq_6_1
 f_4_6 p_4_1 0.5
 p_4_1 f_4_6 0.5
ENDATA
