* SANKHYA pooling instance haverly1, PQ-formulation (#516).
* GENERATED by bench/runners/pooling_models.py from data/pooling/instances/haverly1.json; do not edit.
* Data: Alfaki and Haugland, standard pooling instance Haverly1.gms
* (sha256 3f9f6f740c42fe8d4a7a30c1f3654e478a0598bda1844aefe879ad8e6a424a72).
* Source paper and published optimum: data/pooling/reference.json.
* Minimize total arc cost. Quadratic rows use QCMATRIX (full symmetric, no 1/2).
*
* PQ-formulation (Quesada and Grossmann 1995; Tawarmalani and Sahinidis 2002)
NAME haverly1_pq
ROWS
 N cost
 L src_1
 L src_2
 L src_3
 L dem_5
 L dem_6
 E sumq_4
 L cap_4
 L tq_5_1
 L tq_6_1
 E path_1_4_5
 E path_1_4_6
 E path_2_4_5
 E path_2_4_6
 E rlt_4_5
 E rlt_4_6
 L rltc_1_4
 L rltc_2_4
COLUMNS
 q_1_4 sumq_4 1
 q_1_4 rltc_1_4 -300
 q_2_4 sumq_4 1
 q_2_4 rltc_2_4 -300
 f_3_5 cost 1
 f_3_5 src_3 1
 f_3_5 dem_5 1
 f_3_5 tq_5_1 -0.5
 f_3_6 cost -5
 f_3_6 src_3 1
 f_3_6 dem_6 1
 f_3_6 tq_6_1 0.5
 f_4_5 cost -9
 f_4_5 dem_5 1
 f_4_5 cap_4 1
 f_4_5 tq_5_1 -2.5
 f_4_5 rlt_4_5 -1
 f_4_6 cost -15
 f_4_6 dem_6 1
 f_4_6 cap_4 1
 f_4_6 tq_6_1 -1.5
 f_4_6 rlt_4_6 -1
 v_1_4_5 cost 6
 v_1_4_5 src_1 1
 v_1_4_5 tq_5_1 3
 v_1_4_5 path_1_4_5 1
 v_1_4_5 rlt_4_5 1
 v_1_4_5 rltc_1_4 1
 v_1_4_6 cost 6
 v_1_4_6 src_1 1
 v_1_4_6 tq_6_1 3
 v_1_4_6 path_1_4_6 1
 v_1_4_6 rlt_4_6 1
 v_1_4_6 rltc_1_4 1
 v_2_4_5 cost 16
 v_2_4_5 src_2 1
 v_2_4_5 tq_5_1 1
 v_2_4_5 path_2_4_5 1
 v_2_4_5 rlt_4_5 1
 v_2_4_5 rltc_2_4 1
 v_2_4_6 cost 16
 v_2_4_6 src_2 1
 v_2_4_6 tq_6_1 1
 v_2_4_6 path_2_4_6 1
 v_2_4_6 rlt_4_6 1
 v_2_4_6 rltc_2_4 1
RHS
 rhs src_1 300
 rhs src_2 300
 rhs src_3 300
 rhs dem_5 100
 rhs dem_6 200
 rhs sumq_4 1
 rhs cap_4 300
BOUNDS
 UP bnd q_1_4 1
 UP bnd q_2_4 1
 UP bnd f_3_5 100
 UP bnd f_3_6 200
 UP bnd f_4_5 100
 UP bnd f_4_6 200
 UP bnd v_1_4_5 100
 UP bnd v_1_4_6 200
 UP bnd v_2_4_5 100
 UP bnd v_2_4_6 200
QCMATRIX path_1_4_5
 f_4_5 q_1_4 -0.5
 q_1_4 f_4_5 -0.5
QCMATRIX path_1_4_6
 f_4_6 q_1_4 -0.5
 q_1_4 f_4_6 -0.5
QCMATRIX path_2_4_5
 f_4_5 q_2_4 -0.5
 q_2_4 f_4_5 -0.5
QCMATRIX path_2_4_6
 f_4_6 q_2_4 -0.5
 q_2_4 f_4_6 -0.5
ENDATA
