// SPDX-License-Identifier: Apache-2.0
// SANKHYA - the learned engine selection's decision tree (#477), behind
// algorithm_selection=learned. GENERATED by bench/runners/engine_selection_cart.py from
// bench/results/engine-selection-bcf2e42.csv; regenerate it rather than edit it (the command is
// in that script's docstring), then run scripts/format.sh.
//
// CART (Breiman, Friedman, Olshen and Stone, Classification and Regression Trees, 1984):
// Gini impurity, depth at most 4, at least 3 training rows per leaf. Algorithm
// selection from instance features: Rice, "The algorithm selection problem", Advances in
// Computers 15 (1976); Kotthoff, "Algorithm selection for combinatorial search problems: a
// survey", AI Magazine 35(3) (2014).
//
// Trained on 120 generated instances from 24 shapes, none of them an instance any
// reported benchmark runs (bench/engine_selection/train.txt). On the 30 held-out instances
// of the other shapes (test.txt) it picks the fastest engine, or one within the tie margin of
// it, on 27 and loses 0.5 s in all against the fastest; the rule table does
// so on 17 and loses 161.9 s. Each comment below says how many training rows
// reached that point and which engine was fastest on them (the label, tie margin included).

#include "core/engine_selection_tree.hpp"

namespace sankhya {
namespace {

/// Append one test to the path the log prints.
void take(LearnedTreeChoice* c, const char* test) {
  if (!c->path.empty()) c->path += " and ";
  c->path += test;
}

}  // namespace

LearnedTreeDomain learned_tree_domain() {
  // The largest training instance: past either, the tree has seen nothing like the model.
  return LearnedTreeDomain{9000, 160000};
}

bool learned_tree_reads_symbolic() {
  // No test below reads the symbolic Cholesky fields.
  return false;
}

LearnedTreeChoice learned_engine_tree(const EngineFeatures& f) {
  LearnedTreeChoice c;
  // 120 training rows reach this test: dual-simplex 80, ipm 15, pdhg 25.
  if (static_cast<double>(f.nonzeros) <= 50000.0) {
    take(&c, "nonzeros <= 50000");
    // 90 training rows reach this test: dual-simplex 80, ipm 9, pdhg 1.
    if (static_cast<double>(f.normal_equations_ratio) <= 27.0) {
      take(&c, "normal_equations_ratio <= 27");
      // 85 training rows end here: dual-simplex 80, ipm 4, pdhg 1.
      c.algorithm = "dual-simplex";
      return c;
    }
    take(&c, "normal_equations_ratio > 27");
    // 5 training rows end here: dual-simplex 0, ipm 5, pdhg 0.
    c.algorithm = "ipm";
    return c;
  }
  take(&c, "nonzeros > 50000");
  // 30 training rows reach this test: dual-simplex 0, ipm 6, pdhg 24.
  if (static_cast<double>(f.equality_row_share) <= 0.68) {
    take(&c, "equality_row_share <= 0.68");
    // 25 training rows end here: dual-simplex 0, ipm 1, pdhg 24.
    c.algorithm = "pdhg";
    return c;
  }
  take(&c, "equality_row_share > 0.68");
  // 5 training rows end here: dual-simplex 0, ipm 5, pdhg 0.
  c.algorithm = "ipm";
  return c;
}

}  // namespace sankhya
