// SPDX-License-Identifier: Apache-2.0
// SANKHYA - the learned LP engine selection (#477): a shallow decision tree over the model
// features of engine_features.hpp, trained on our own benchmark runs and committed as
// readable C++ rules (engine_selection_tree.cpp, generated by
// bench/runners/engine_selection_cart.py), consulted by select_engine() when
// algorithm_selection=learned. The default stays the hand-written rule table (#284).
//
// Rice, "The algorithm selection problem", Advances in Computers 15 (1976): the problem is
// a map from a feature space of instances to an algorithm space, judged by performance on
// the instances. Kotthoff, "Algorithm selection for combinatorial search problems: a
// survey", AI Magazine 35(3) (2014): per-instance selection by a classifier trained offline
// on measured runs. Breiman, Friedman, Olshen and Stone, "Classification and Regression
// Trees" (1984): the classifier, chosen because its rules can be read and reviewed.
#pragma once

#include <string>

#include "core/engine_features.hpp"

namespace sankhya {

/// What the tree chose and the tests it passed on the way, joined by " and ", e.g.
/// "rows > 1500 and cholesky_fill_ratio <= 20". Empty when the tree is a single leaf.
struct LearnedTreeChoice {
  std::string algorithm;  ///< "dual-simplex", "ipm" or "pdhg"
  std::string path;
};

/// The largest training instance. The tree is consulted only for a model no larger in rows
/// and nonzeros: beyond that it has seen nothing like the model, and the rule table, whose
/// thresholds were measured up to the 779,640-row refinery, decides.
struct LearnedTreeDomain {
  Index max_rows = 0;
  Count max_nonzeros = 0;
};

/// The tree. When learned_tree_reads_symbolic() is true it tests the symbolic Cholesky
/// fields, and `f` must come from compute_engine_features(model, /*symbolic=*/true).
[[nodiscard]] LearnedTreeChoice learned_engine_tree(const EngineFeatures& f);

[[nodiscard]] LearnedTreeDomain learned_tree_domain();

/// Whether any test of the tree reads cholesky_nonzeros or cholesky_fill_ratio. When none
/// does, the selection skips the symbolic pass (0.2 s on dfl001, against 0.1 ms for the
/// one-pass features).
[[nodiscard]] bool learned_tree_reads_symbolic();

}  // namespace sankhya
